### PR TITLE
ADBDEV-4606: ORCA generates incorrect plan with exists clause for partitioned table

### PR DESCRIPTION
**Pull request by RekGRpth**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/58573

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795727

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795724

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795723

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795728

**Comment by RekGRpth** [comment]
This patch is broken by
```sql
EXPLAIN (ANALYZE off, COSTS off, VERBOSE on)
SELECT * FROM (values (1), (2)) a WHERE EXISTS (
    SELECT * FROM (values (3), (4)) as b
);
2023-11-17 12:44:59:687907 +05,THD000,ERROR,"../../../../../../src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h:1115: Failed assertion: __null != pcrInner
Stack trace:
1    0x0000000000f630b8 gpos::CErrorContext::Record + 178
2    0x0000000000f6402e gpos::CException::Raise + 256
3    0x0000000001231035 gpopt::CExpression* gpopt::CUtils::PexprLogicalApply + 209
4    0x000000000122ecf1 gpopt::CSubqueryHandler::FRemoveExistentialSubquery + 571
5    0x000000000122edcd gpopt::CSubqueryHandler::FRemoveExistsSubquery + 133
6    0x000000000122f3d4 gpopt::CSubqueryHandler::FProcessScalarOperator + 432
7    0x000000000122f56b gpopt::CSubqueryHandler::FProcess + 151
8    0x000000000128e499 gpopt::CXformSubqueryUnnest::PexprSubqueryUnnest + 325
9    0x000000000128e783 gpopt::CXformSubqueryUnnest::Transform + 69
10   0x000000000128e8c7 gpopt::CXformSubqueryUnnest::Transform + 291
11   0x00000000011b5467 gpopt::CGroupExpression::Transform + 857
12   0x00000000011d0f37 gpopt::CJobTransformation::EevtTransform + 199
13   0x00000000011d1498 gpopt::CJobStateMachine + 330
14   0x00000000011d1054 gpopt::CJobTransformation::FExecute + 110
15   0x00000000011d7779 gpopt::CScheduler::FExecute + 77
16   0x00000000011d717f gpopt::CScheduler::ExecuteJobs + 97
17   0x00000000011d7116 gpopt::CScheduler::Run + 50
18   0x00000000010ed141 gpopt::CEngine::Optimize + 853
19   0x00000000011a2fc4 gpopt::COptimizer::PexprOptimize + 84
20   0x00000000011a29da gpopt::COptimizer::PdxlnOptimize + 1244
21   0x00000000012f8422 COptTasks::OptimizeTask + 1358
22   0x0000000000f77bfd gpos::CTask::Execute + 171
23   0x0000000000f7a335 gpos::CWorker::Execute + 175
24   0x0000000000f76178 gpos::CAutoTaskProxy::Execute + 190
25   0x0000000000f7c2c4 gpos_exec + 755
26   0x00000000012f726a COptTasks::Execute + 192
27   0x00000000012f9039 COptTasks::GPOPTOptimizedPlan + 139
28   0x00000000012f9d7d CGPOptimizer::GPOPTOptimizedPlan + 73
29   0x00000000012fa32d GPOPTOptimizedPlan + 35
30   0x0000000000bf5e5d optimize_query + 464
31   0x0000000000bd8e33 standard_planner + 152
",
LOG:  Pivotal Optimizer (GPORCA) failed to produce plan (unexpected)
                  QUERY PLAN                  
----------------------------------------------
 Result
   Output: "*VALUES*".column1
   One-Time Filter: $0
   InitPlan 1 (returns $0)
     ->  Limit
           Output: "*VALUES*_1".column1
           ->  Values Scan on "*VALUES*_1"
                 Output: "*VALUES*_1".column1
   ->  Values Scan on "*VALUES*"
         Output: "*VALUES*".column1
 Optimizer: Postgres query optimizer
 Settings: optimizer=on
(12 rows)
```

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/58587

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/796140

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/796141

**Pull request closed without merging**
