### PR TITLE
Make frozen_insert_crash test stable

### PR DESCRIPTION
**Pull request by whitehawk**
Make frozen_insert_crash test stable

Commit 8accc02 introduced a new flaking test. The test expects a panic to occur
in the process that performs the insert. But sometimes the panic happens first
in process which started by dtx recovery process that periodically checks for
orphaned transactions. Which leads to an error in the test. The solution is to
panic only the required process, which is done by extracting session from
pg_stat_activity by query.

Cherry-pick of 3d4cc61b6d697e7eb524078285d8dfbb19949e57

### CODE REVIEW

**Comment by RekGRpth** [comment]
> Commit [1502bef](https://github.com/arenadata/gpdb/commit/1502befb5be3a511d287d9eff694bb1c0434156f) introduced a new flaking test

that commit belongs to 6X

**Comment by RekGRpth** [comment]
> > Commit [1502bef](https://github.com/arenadata/gpdb/commit/1502befb5be3a511d287d9eff694bb1c0434156f) introduced a new flaking test
> 
> that commit belongs to 6X

I meant to change it in the commit description, not the pull request. Because the patch will be merged as a backport with a description from a commit, and not from a pull request. Specifically, I propose changing 1502bef to 8accc02.

**Comment by RekGRpth** [comment]
Also, the commit's message should contain a cherry-peak of what commit it was.

**Comment by whitehawk** [comment]
> Also, the commit's message should contain a cherry-peak of what commit it was.

Is it also required to change the PR ID in the commit description from #893 to #931?

**Comment by RekGRpth** [comment]
> > Also, the commit's message should contain a cherry-peak of what commit it was.
> 
> Is it also required to change the PR ID in the commit description from #893 to #931?

I don't know, but I wouldn't put the PR ID in the commit message.

**Review by RekGRpth — APPROVED** [review]

**Review by bandetto — APPROVED** [review]

**Pull request merged**
