### PR TITLE
ADBDEV-6834: Fix modified GUCs when starting a new slice

### PR DESCRIPTION
**Pull request by RekGRpth**
Fix modified GUCs when starting a new slice

The commit 2b821ea added installation of modified GUCs when starting a new
slice. However, it was not taken into account that some GUCs, for example,
default_tablespace, temp_tablespaces and temp_spill_files_tablespaces, cannot
contain invalid values ​​for a new connection, although this does not cause
problems for the current connection. This patch fixes an issue by using the
PGC_S_TEST option instead of PGC_S_SESSION when setting modified GUCs when
starting a new slice.

### CODE REVIEW

**Comment by bandetto** [comment]
Can you please add something like `7X` to the title to differentiate between two PRs?

**Comment by RekGRpth** [comment]
> Can you please add something like `7X` to the title to differentiate between two PRs?

I suggested adding 6X and 7X labels, but this suggestion was rejected because "it's already clear which version the pull request is being made for."

screen

**Comment by bandetto** [comment]
It still requires to hoverover the PR label or waiting for the page to load which is mildly inconvenient. Alright.

**Review by bandetto — DISMISSED** [review]

**Comment by whitehawk** [comment]
Why don't you wait for #1148 to complete and do a cherry-pick? I think it is better, as it will allow to preserve traceability to #1148, where discussion is more detailed.

**Comment by RekGRpth** [comment]
> Why don't you wait for #1148 to complete and do a cherry-pick? I think it is better, as it will allow to preserve traceability to #1148, where discussion is more detailed.

Done.

**Review by whitehawk — APPROVED** [review]

**Review by bandetto — APPROVED** [review]

**Pull request merged**
