### PR TITLE
Replace memcpy with memmove in SWAPN macro

### PR DESCRIPTION
**Pull request by whitehawk**
Replace memcpy with memmove in SWAPN macro

memcpy was used to copy overlapping buffers in the SWAPN macro. For memcpy, 
according to its specification, "if the objects overlap, the behavior is 
undefined". Thus, it may potentially cause errors. The memcpy function is 
replaced with memmove, which also copies data from one buffer to another one,
but the buffers may overlap according to its specification.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68118

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1233372

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1233373

**Review by RekGRpth — APPROVED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68247

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1235831

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1235832

**Pull request merged**
