### PR TITLE
Fix flaky regression test explain_format

### PR DESCRIPTION
**Pull request by red1452**
Fix flaky regression test explain_format

Hash Join node may have the "Extra Text" message, which is printed at the
ExecHashTableExplainEnd function. It is printed if the total_buckets counter is
more than zero.

At commit 61de7b3bb63c45a18ea3c90c2e14e8e4bc829120 MPP buffer usage and I/O
timings were added to the explain's output. These counters are copied to buffer
at the cdbexplain_collectStatsFromNode function. This buffer contains all
statistics of node, and this buffer will be sent to dispatcher. These counters
are used by the ExplainNode function to print non-zero values. Also, this commit
added copying "Extra text" message if one (or more) counters is more than zero
to the cdbexplain_depositStatsToNode function. It lead to printing "Extra text"
message, when it is not needed.

MPP buffer usage and I/O timings are not printed at the "Extra text". "Extra
text" is printed on segments, but these counters are processed at the
dispatcher. It means, that copying "Extra text" message if one (or more)
counters is more than zero, was added by a mistake.

This patch removes copying "Extra text" message from the
cdbexplain_depositStatsToNode function.

### CODE REVIEW

**Comment by InnerLife0** [comment]
The given patch looks like covering up the symptoms of a problem. It still unclear what is the reason of flaky shared_blks_hit value and is this a real problem (if it really). Without explaining this, patch tries to fix the output.

**Comment by red1452** [comment]
> The given patch looks like covering up the symptoms of a problem. It still unclear what is the reason of flaky shared_blks_hit value and is this a real problem (if it really). Without explaining this, patch tries to fix the output.

My patch optimizes using "Extra Text" for Hash join node. This string is useless, if it has zero at average, max and used counters of buckets. This "Extra text" is printed for non-standart counters. The `cdbexplain_depositStatsToNode` function (which prints "Extra text") has comment about non-standart counters: It should be printed based on the number of output rows. At the our example with error all nodes return zero rows:
```
QUERY PLAN
Gather Motion 3:1  (slice1; segments: 3) (actual time=33.780..33.794 rows=0 loops=1)
  Output: s1.b
  ->  Hash Join (actual time=0.000..32.079 rows=0 loops=1)
        Output: s1.b
        Hash Cond: (s2.b = s1.b)
        work_mem: 24576kB  Segments: 3  Max: 8192kB (segment 0)  Workfile: (0 spilling)
        Extra Text: (seg0)   Hash chain length 0.0 avg, 0 max, using 0 of 1048576 buckets.
        ->  Seq Scan on public.stat_io_timing s2 (never executed)
              Output: s2.a, s2.b
        ->  Hash (actual time=0.000..24.777 rows=0 loops=1)
              Output: s1.b
              Buckets: 1048576  Batches: 1  Memory Usage: 8192kB
              ->  Broadcast Motion 1:3  (slice2; segments: 1) (actual time=0.000..24.774 rows=0 loops=1)
                    Output: s1.b
                    ->  Seq Scan on public.stat_io_timing s1 (actual time=0.000..8.841 rows=0 loops=1)
                          Output: s1.b
                          Filter: (s1.a = 50)
Optimizer: Postgres-based planner
Settings: Planning Time: 0.682 ms
  (slice0)    Executor memory: 39K bytes.
  (slice1)    Executor memory: 8207K bytes avg x 3 workers, 8207K bytes max (seg0).  Work_mem: 8192K bytes max.
  (slice2)    Executor memory: 41K bytes (seg1).
Memory used:  256000kB
Execution Time: 40.806 ms
(25 rows)
```

**Comment by red1452** [comment]
`shared_blks_hit` is counter, which shows how times did process find buffer at the shared memory. It is calculated at only one [place](https://github.com/arenadata/gpdb/blob/adb-7.1.0/src/backend/storage/buffer/bufmgr.c#L852). It is incremented, if the `BufferAlloc` function set true to the `foundPtr` pointer. It may be if it have already done the desired page. Before sending statistics to dispatcher, executors [calculate](https://github.com/arenadata/gpdb/blob/adb-7.1.0/src/backend/executor/instrument.c#L132) difference at the counters (current counters minus start counters). `shared_blks_hit` is also used at [showing statistics](https://github.com/arenadata/gpdb/blob/adb-7.1.0/src/backend/commands/explain.c#L3922-L3923). It may be more than zero.

**Comment by InnerLife0** [comment]
1) The behavior of cdbexplain_depositStatsToNode() is different on 6x and 7x. What was the purpose of commit, which extended the logic in 7x?
2) What additional text this changes print to plan? Is this changes printed by `(shared_blks_hit.agg.vsum > 0)` or similar conditions?
3) What if `(stats->chainlength.vcnt > 0)` and `(shared_blks_hit.agg.vsum > 0)` will be true together? Is "Extra Text: ..." message printed by `(shared_blks_hit.agg.vsum > 0)` still relevant to commit purpose?
4) Why conditions don't use 1.05 multiplier? Is it correct to apply it?
5) Why do we get cache hits at first call by don't get them at second call?

**Comment by red1452** [comment]
> 1. The behavior of cdbexplain_depositStatsToNode() is different on 6x and 7x. What was the purpose of commit, which extended the logic in 7x?

Behavior of cdbexplain_depositStatsToNode was changed by [commit](https://github.com/arenadata/gpdb/commit/61de7b3bb63c45a18ea3c90c2e14e8e4bc829120). This commit adds printing values of the buffer counters to the explain's output. But this values are not printed over "Extra text", it does at the `ExplainNode` function by calling `show_buffer_usage`.

> 2. What additional text this changes print to plan? Is this changes printed by `(shared_blks_hit.agg.vsum > 0)` or similar conditions?

This text looks like:
```
        Buffers: shared hit=8 read=3
        I/O Timings: read=0.087
```
These lines are not printed by `(shared_blks_hit.agg.vsum > 0)` or similar conditions. It prints at `show_buffer_usage`.

> 3. What if `(stats->chainlength.vcnt > 0)` and `(shared_blks_hit.agg.vsum > 0)` will be true together? Is "Extra Text: ..." message printed by `(shared_blks_hit.agg.vsum > 0)` still relevant to commit purpose?

First of these conditions copies "Extra text" from segment's buffer to the explain's output. Others will do nothing.

> 4. Why conditions don't use 1.05 multiplier? Is it correct to apply it?

As I said, these conditions are useless, because buffer counters are printed at the other place.

**Comment by InnerLife0** [comment]
All is OK except of this sentence.

> These counters are sent from segments to dispatcher by the cdbexplain_collectStatsFromNode function.

This function doesn't send counters.

**Comment by red1452** [comment]
> All is OK except of this sentence.
> 
> > These counters are sent from segments to dispatcher by the cdbexplain_collectStatsFromNode function.
> 
> This function doesn't send counters.

Yes, but this function prepares buffer, which will be sent to dispatcher. This buffer contains all statistics of node.

**Comment by InnerLife0** [comment]
> Yes, but this function prepares buffer, which will be sent to dispatcher. This buffer contains all statistics of node.

This doesn't justify the confusing comment.

**Comment by red1452** [comment]
> This doesn't justify the confusing comment.

I updated description.

**Review by InnerLife0 — APPROVED** [review]

**Pull request merged**
