### PR TITLE
ADBDEV-5068: Make the behave tests more stable

### PR DESCRIPTION
**Pull request by KnightMurloc**
Make the behave tests more stable

When initializing containers for behave tests, ssh host keys are created. These
keys are scanned by each container using ssh-keyscan. Because all the containers
are initialized in parallel, a race condition took place. If some containers has
not yet managed to create keys, while the other container has already started
the scanning stage, then the container does not add the keys of some containers
to known_hosts. Lack of a host key in known_hosts led to the failure of the ssh
connection during the tests.

This patch splits container initialization to make host keys scan after
containers initialization when all containers have created host keys.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/66079

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1132888

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1132889

**Review by RekGRpth — APPROVED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/66119

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1135580

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1135581

**Pull request merged**
