### PR TITLE
ADBDEV-1844 ADB 5.28.12 sync

### PR DESCRIPTION
**Pull request by deart2k**

### CODE REVIEW

**Review by maksm90 — APPROVED** [review]

**Comment by leskin-in** [comment]
The tests seem to fail for some reason unrelated to this PR. @deart2k

**Comment by deart2k** [comment]
> The tests seem to fail for some reason unrelated to this PR. @deart2k
Tests were failed because image pivotaldata/centos-gpdb-dev:7-gcc6.2-llvm3.7  not available. @Stolb27 You told about it. We know how resolve this problem?

**Comment by Stolb27** [comment]
@deart2k we are waiting for merge https://github.com/arenadata/gpdb/pull/224 now

**Comment by Stolb27** [comment]
> @deart2k we are waiting for merge #224 now

#224 was merged. So, we are waiting for tests.

**Pull request closed without merging**
