### PR TITLE
6.11.0 sync

### PR DESCRIPTION
**Pull request by deart2k**

### CODE REVIEW

**Review by leskin-in — APPROVED** [review]
Note:
* https://github.com/arenadata/gpdb/pull/115/commits/6a6da69f018685459e1c5e5fa4e6b1b0080e9fc8 forbids to build `postgres_fdw` on MacOS. @darthunix 
* https://github.com/arenadata/gpdb/pull/115/commits/4d248acb70b73461e3d833675ed7a06db90268de closes [ADBDEV-103](https://arenadata.atlassian.net/browse/ADBDEV-103). We may need to conduct a test of the case described there and add a confirmation to JIRA.

**Comment by leskin-in** [comment]
I suppose @maksm90 should be added to the reviewers of this PR (and all similar PRs in the future). @Stolb27 please correct me if this should not be done.

**Comment by Stolb27** [comment]
> We may need to conduct a test of the case described there and add a confirmation to JIRA.

@leskin-in  We already merged this fix in [6X](https://github.com/arenadata/gpdb/pull/109) and [5X](https://github.com/arenadata/gpdb/pull/104). What do you mean?

> I suppose @maksm90 should be added to the reviewers of this PR (and all similar PRs in the future).

Yes, of course. There are several fixes by Maksim in this Pivotal release.

@maksm90, the main purpose of these reviews is the detection of upstream changes that may break our fork.

**Review by Stolb27 — APPROVED** [review]

**Comment by leskin-in** [comment]
@Stolb27 although they were merged earlier, I suppose we could conduct the tests again, as we are re-importing the change from upstream. In the current case this is likely of little (if any) value, but I suppose this is a good practice we should follow, as not all changes re-imported are exactly the same as the ones made to our fork.

**Review by maksm90 — APPROVED** [review]

**Pull request merged**
