### PR TITLE
Free serveraddrs on error

### PR DESCRIPTION
**Pull request by dnskvlnk**
serveraddrs is not free in a case of error, this patch frees it

### CODE REVIEW

**Comment by andr-sokolov** [comment]
serveraddrs should be freed before every return in the function

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68020

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1228741

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68064

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1229922

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1229923

**Review by RekGRpth — APPROVED** [review]
Create a pull request description with a title and body.

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68267

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1239295

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1239297

**Comment by BenderArenadata** [comment]
Failed job Behave tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1239292

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68539

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1252478

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1252479

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1252467

**Pull request closed without merging**
