### PR TITLE
Sync 6.26.2 changes

### PR DESCRIPTION
**Pull request by BenderArenadata**
742bf6f, fc2aade conflict with 08d747e
6425610 conflicts with b72ff6b
5a10d0a conflicts with b72ff6b
93d4623 conflicts with cb1a87c
611ff8a, ebd310c, 55e1511 conflict with 9290a5c
9290a5c output need to be duplicated for power

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/992322

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/992321

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/66676

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1162925

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1162926

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1162920

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/66716

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1165650

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1165651

**Review by Stolb27 — APPROVED** [review]

**Review by bimboterminator1 — APPROVED** [review]

**Review by RekGRpth — APPROVED** [review]

**Pull request merged**
