### PR TITLE
Sync 6.26.0 changes

### PR DESCRIPTION
**Pull request by BenderArenadata**
### Patches to revert:

1. 6298e77 conflicts with 02e2246. Re-applied as fc2aade
2. 1c2c49c, bef7c8d, ca89de3 was replace by upstream 720464e
3. cc35273 conflicts with c381149. Re-applied as 3c95046
4. c164546, 96e6caa, d0a5bc0, 0b4466d, 4a9aac4 conflicts with 2189e1f. Re-applied as 55e1511, ebd310c, 611ff8a

### Additional patches for release:
1. Output from 720464e and 2189e1f was migrated to subselect_gp_1 for ppc64le in 56f634a and d7bab76
2. 885a55d cherry-picked from 5d8810d to solve flaky test added by 90b4548
3. 8d8007e reverts upstream 7f3c91f. This patch breaks resource releasing logic in the environment where ipv6 disabled (e.g. our CI). We should clarify, that problem doesn't affect production clusters first (see [ADBDEV-4727](https://tracker.yandex.ru/ADBDEV-4727)).

### Other notes
1. ABI tests will be fixed later, see [ADBDEV-4719](https://tracker.yandex.ru/ADBDEV-4719)

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/791676

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/791675

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/845922

**Comment by BenderArenadata** [comment]
Failed job Behave tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/847364

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/847358

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/847360

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/59717

**Comment by BenderArenadata** [comment]
Failed job Behave tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/848815

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/848809

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/848808

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/848811

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/848810

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/59754

**Comment by BenderArenadata** [comment]
Failed job Behave tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/851207

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/851208

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/851209

**Review by RekGRpth — APPROVED** [review]

**Review by dnskvlnk — APPROVED** [review]

**Review by bimboterminator1 — APPROVED** [review]

**Pull request merged**
