### PR TITLE
Fix EnableXform() & DisableXform() functions when optimizer is off

### PR DESCRIPTION
**Pull request by whitehawk**
Fix EnableXform() & DisableXform() functions when optimizer is off

Problem:
If a session was started with disabled 'optimizer' GUC, and EnableXform() or
DisableXform() was called from a query, the query failed with a crash. The issue
was found on 'rowhints' test.

Cause:
The functions mentioned above tried to access internal Orca's structures, that
were not initialized, as the init was done during first planning only if
'optimizer' was on.

Fix:
Init Orca when planner is invoked first time regardless the value of
'optimizer'.

Note:
One can think that it is better to perform Orca init somewhen at the backend
init. But we'd like to keep Orca init after GPMemoryProtect_Init() (as it was
before Orca moved to an extension). And there is no existing standard hook to
call after GPMemoryProtect_Init() and before PostgresMain() enters its main
loop. Thus it is where it is.

No new tests are added, as existing 'rowhints' test can catch this issue.

----------

Better to review the delta with 'Hide whitespaces' enabled.

### CODE REVIEW

**Review by silent-observer — APPROVED** [review]
LGTM. However, you should explicitly specify in the description why no new test is added (because 'rowhints' is already sufficient for testing this)

**Comment by whitehawk** [comment]
> LGTM. However, you should explicitly specify in the description why no new test is added (because 'rowhints' is already sufficient for testing this)

Ok, added to the description.

**Comment by dkovalev1** [comment]
Have you considered initializing ORCA in _PG_init? It seems to be the right place for such initialization.

Lazy loading is nice, but it introduces a delay on the first query to the backend, i.e., when establishing a new connection, unlike preloading during backend startup. This might cause unexpected delays in the user's queries.

**Comment by whitehawk** [comment]
> Have you considered initializing ORCA in _PG_init? It seems to be the right place for such initialization.
> 
> Lazy loading is nice, but it introduces a delay on the first query to the backend, i.e., when establishing a new connection, unlike preloading during backend startup. This might cause unexpected delays in the user's queries.

I considered it, but the approach with _PG_init() has several disadvantages:
 - we will not be able to call `gp_orca_shutdown()`, because when backend is started, it [clears the callbacks registered by postmaster](https://github.com/arenadata/gpdb/blob/534fe5f5a45d16b3c8c10877cb50849c7755de3e/src/backend/utils/init/miscinit.c#L307)
 - in this case we'll call `InitGPOPT()`, that makes allocations, before `GPMemoryProtect_Init()`, which also doesn't sound good.

So I've come up with current approach.

**Comment by dkovalev1** [comment]
> > Have you considered initializing ORCA in _PG_init? It seems to be the right place for such initialization.
> > Lazy loading is nice, but it introduces a delay on the first query to the backend, i.e., when establishing a new connection, unlike preloading during backend startup. This might cause unexpected delays in the user's queries.
> 
> I considered it, but the approach with _PG_init() has several disadvantages:
> 
>     * we will not be able to call `gp_orca_shutdown()`, because when backend is started, it [clears the callbacks registered by postmaster](https://github.com/arenadata/gpdb/blob/534fe5f5a45d16b3c8c10877cb50849c7755de3e/src/backend/utils/init/miscinit.c#L307)
> 
It's also a question - when to call gp_orca_shutdown() now. User can call DROP EXTENSION, in this case it seems logical to have it in that time. We are not tied to the backend life cycle anymore.

>     * in this case we'll call `InitGPOPT()`, that makes allocations, before `GPMemoryProtect_Init()`, which also doesn't sound good.
GPMemoryProtect_Init() is called from InitPostgres() from PostgresMain(). Can the extension be loaded before it?

**Comment by whitehawk** [comment]
> User can call DROP EXTENSION

User doesn't create an extension for Orca currently. All that is needed is to add orca to shared_preload_libraries. `CREATE/DROP EXTENSION` is not needed.

> It's also a question - when to call gp_orca_shutdown() now.

So, gp_orca_shutdown() is now called on before_shmem_exit callback. At almost the same time `ShutdownPostgres()` is called, where de-init was before.  

> GPMemoryProtect_Init() is called from InitPostgres() from PostgresMain(). Can the extension be loaded before it?

Again, we do not call `CREATE EXTENSION`. Orca will be inited on first planner invocation by the backend, which should be possible when backend has inited, and ready to dispatch.

**Comment by dkovalev1** [comment]
> > User can call DROP EXTENSION
> 
> User doesn't create an extension for Orca currently. All that is needed is to add orca to shared_preload_libraries. `CREATE/DROP EXTENSION` is not needed.
> 
> > It's also a question - when to call gp_orca_shutdown() now.
> 
> So, gp_orca_shutdown() is now called on before_shmem_exit callback. At almost the same time `ShutdownPostgres()` is called, where de-init was before.
> 
> > GPMemoryProtect_Init() is called from InitPostgres() from PostgresMain(). Can the extension be loaded before it?
> 
> Again, we do not call `CREATE EXTENSION`. Orca will be inited on first planner invocation by the backend, which should be possible when backend has inited, and ready to dispatch.



> > User can call DROP EXTENSION
> 
> User doesn't create an extension for Orca currently. All that is needed is to add orca to shared_preload_libraries. `CREATE/DROP EXTENSION` is not needed.
> 
> > It's also a question - when to call gp_orca_shutdown() now.
> 
> So, gp_orca_shutdown() is now called on before_shmem_exit callback. At almost the same time `ShutdownPostgres()` is called, where de-init was before.
> 
> > GPMemoryProtect_Init() is called from InitPostgres() from PostgresMain(). Can the extension be loaded before it?
> 
> Again, we do not call `CREATE EXTENSION`. Orca will be inited on first planner invocation by the backend, which should be possible when backend has inited, and ready to dispatch.

okay, I got it now

**Review by dkovalev1 — APPROVED** [review]

**Pull request merged**
