### PR TITLE
Sync 6.25.2 changes

### PR DESCRIPTION
**Pull request by BenderArenadata**
Related fixes:

1. 94a021e by @andr-sokolov
2. 9d65b5b by @red1452 
3. d06ab8a by @red1452 
4. c7c17f9 by @InnerLife0 🎉 (conflicts with our 99de02b). There are some difference in handling dispatching to QE errors. We should reapply our patch partially.
5. cbaf739 by @red1452  (our patch 25cabd4 was reverted, as a result, default value was changed)
6. b85bff4 by @RekGRpth 
7. c7c0d83 by @RekGRpth 
8. f1d6072 allows removing old zstd diff (c8754cf) with upstream (WIP)
9. 8ada6cb by @Stolb27 was merged but then reverted in 7effe33 because of break down upstream CI. Our CI seems to be not affected
10. 52bbf95 breaks resource group tests. We need to modify test pipelines to fix this issue. Will be done [later](https://tracker.yandex.ru/ADBDEV-4415).

Commits to reapply:
1. 9493f8c conflicts with 585c90f
2. a5b5c04 conflicts with 9e03478
3. 12ca120 conflicts with c7c17f9 
4. 99de02b should be reapplied partially (WIP)

### CODE REVIEW

**Comment by Stolb27** [comment]
Related fixes:

1. 94a021e by @andr-sokolov
2. 9d65b5b by @red1452 
3. d06ab8a by @red1452 
4. c7c17f9 by @InnerLife0 🎉 
5. cbaf739 by @red1452 
6. b85bff4 by @RekGRpth 
7. c7c0d83 by @RekGRpth 
8. f1d6072 allows to remove old zstd diff with upstream
9. 8ada6cb by @Stolb27 was merged but then reverted in 7effe33 because break down upstream CI. Our CI seems to be not affected

**Review by RekGRpth — APPROVED** [review]

**Review by InnerLife0 — APPROVED** [review]

**Review by red1452 — APPROVED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/55942

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/674138

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/674136

**Review by Stolb27 — APPROVED** [review]

**Pull request merged**
