### PR TITLE
ADBDEV-6278: pg_dump incorrectly generate cleanup for external tables (#1045)

### PR DESCRIPTION
**Pull request by silent-observer**
pg_dump incorrectly generate cleanup for external tables (#1045)

Fixes issue #1025. DROP EXTERNAL TABLE in pg_dump output had incorrect syntax,
this patch fixes the typo.

Ticket: ADBDEV-6257

Changes from original commit:
1. Removed tests since this code only affects GPDB 6 compatibility, there is
no way to reach this line using only GPDB 7. This is because GPDB 7 uses
FOREIGN TABLE instead of EXTERNAL TABLE, so EXTERNAL TABLE cannot appear in
GPDB 7 database.

Co-authored-by: eshkinkot \<eshkinkot@gmail.com\>
(cherry picked from commit eaafa97a524e34f6533b5b5ee406fce5bf430d94)

---

To test this manually, connect to a working GPDB 6's cluster using pg_dump taken from GPDB 7 (GPDB 7 cluster is not necessary).

Note: Do not squash to preserve authorship

### CODE REVIEW

**Comment by RekGRpth** [comment]
> GPDB 7's pg_dump executable should only be applied to GPDB 7's databases

Where did this statement come from?

**Comment by dkovalev1** [comment]
IMHO if you say in the description that EXTERNAL tables were in 6.x, but they are FOREIGN in 7.x, it would be much clearer why there are no tests here.

**Comment by RekGRpth** [comment]
> IMHO if you say in the description that EXTERNAL tables were in 6.x, but they are FOREIGN in 7.x, it would be much clearer why there are no tests here.

This patch is about using the pg_dump binary from 7X with a database from 6X.

**Review by hilltracer — APPROVED** [review]
It is worth mentioning that to check the result, the resulting SQL code must be applied in GPDB7. Therefore, GPDB7 still needs to be run after dumping the table.

**Review by dkovalev1 — APPROVED** [review]

**Pull request merged**
