### PR TITLE
Include <sys/resource.h> for getrlimit and setrlimit

### PR DESCRIPTION
**Pull request by seryozhasmirnov**
Without <sys/resource.h> inlude RLIMIT_CORE is not defined and due
to that in case of fault injector with tipe FaultInjectorTypePanic
the code to avoid core file generation for PANIC is disabled.

As a result core file is generated that affects timing and fills up
disks.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by darthunix** [comment]
@seryozhasmirnov so the current test passes with a fault injector that disables core dump generation. But on production server, these dumps are enabled. So, we still can face a situation when ADB backend is generating a core dump (and our shared memory is possibly corrupted) while the postmaster still forks new backends with undefined behavior. Do I understand the situation correctly?

**Comment by seryozhasmirnov** [comment]
> @seryozhasmirnov so the current test passes with a fault injector that disables core dump generation. But on production server, these dumps are enabled. So, we still can face a situation when ADB backend is generating a core dump (and our shared memory is possibly corrupted) while the postmaster still forks new backends with undefined behavior. Do I understand the situation correctly?

Dear @darthunix,  despite the ulimit settings the will be no core dump generated due to [setrlimit](https://linux.die.net/man/2/setrlimit) call used to [set the maximum core size (RLIMIT_CORE) to 0 in case of FaultInjectorTypePanic](https://github.com/arenadata/gpdb/blob/adb-5.x/src/backend/utils/misc/faultinjector.c#L729-L749).

**Comment by darthunix** [comment]
@seryozhasmirnov maybe I didn't explain my fears properly... Ok, you have fixed the fault injector test - the fault injector panic works correctly and doesn't generate core dumps. But imagine, that we face the situation from the heap corruption test in production without any fault injection and customer collects core dumps.

In this case, the postmaster still can produce new connections while the problem backend raised the fatal error and potentially corrupted shared memory.

**Comment by seryozhasmirnov** [comment]
> @seryozhasmirnov maybe I didn't explain my fears properly... Ok, you have fixed the fault injector test - the fault injector panic works correctly and doesn't generate core dumps. But imagine, that we face the situation from the heap corruption test in production without any fault injection and customer collects core dumps.
> 
> In this case, the postmaster still can produce new connections while the problem backend raised the fatal error and potentially corrupted shared memory.

Dear @darthunix,
Let me try to dissolve your fears. 
If there is a fault with core dump generated it will help to find the problem in the code. After program crash one should not expect the program to continue execution like nothing has happened.
The core dump generation is an abnormal and unexpected behavior that should be avoided by writing flawless code. We should not blame dying program for anything, even for  corrupting memory in the pangs of death. [De mortuis nil nisi bonum](https://en.wikipedia.org/wiki/De_mortuis_nil_nisi_bonum).

Thank you!

**Comment by darthunix** [comment]
@seryozhasmirnov the problem is that the postmaster handles many clients simultaneously and forks them different backends. Imagine: one of the backends crashed and starts generating a core dump, while the others continue to return some undefined results to the clients. These clients would not be pleased with the garbage returned by their backends.

The root of the problem is that in 5X a SIGCHLD handler only sets a flag to terminate child process [later](https://github.com/arenadata/gpdb/blob/13b56a4f575d578cb1f3d1bf1d4f6ff220e33b0c/src/backend/postmaster/postmaster.c#L2417) in the main loop. The only exception is a FTS shutdown request - it is [handled](https://github.com/arenadata/gpdb/blob/13b56a4f575d578cb1f3d1bf1d4f6ff220e33b0c/src/backend/postmaster/postmaster.c#L4363) at the moment the postmaster gets the signal. 

In 6X [any](https://github.com/arenadata/gpdb/blob/18d86c55845cecb9325a338c2f8cc389b877544e/src/backend/postmaster/postmaster.c#L3158) terminating child processes are handled at the moment the signal [arrives](https://github.com/arenadata/gpdb/blob/18d86c55845cecb9325a338c2f8cc389b877544e/src/backend/postmaster/postmaster.c#L721) to postmaster.

I think, that we should change SIGCHLD handling logic in 5X. It would be a good idea to implement a test for the problem discussed above with some long-running core dump generation.

**Comment by seryozhasmirnov** [comment]
Dear @darthunix,

The root cause it that `SIGCHLD` was received after 6 seconds from `abort()` call. Moving code to handle child termination to signal handler will not make `SIGCHLD` to arrive earlier. The traces shows that `SIGCHLD` signals from other processes have been processed after `abort()` call in these 6 seconds.

Thank you!

**Review by darthunix — APPROVED** [review]
Finally, I got the problem. SIGCHLD is sent by the child process exactly when it exits (i.e. after writing a core dump). BTW, there was an [attempt](https://lwn.net/ml/linux-kernel/e7ed306f-8992-9d00-bcab-5131159e8d89@cisco.com/#t) to implement in the Linux core a special pre-core dump signal, but the work was not finished and seems to be abandoned.

I don't know a good solution for this problem, except writing a safe code when the child process works with shared memory (I hope, GPDB has such code). The only possible solution to make things a little safe is to disable the core dumps in OS, but we can't do it as we have to investigate different accidents.

The tests now pass, the fundamental problem is very complicated - so, approve current PR.

**Pull request merged**
