### PR TITLE
Add datadir path to gpsegconfig_dump at cdb dispatcher test

### PR DESCRIPTION
**Pull request by red1452**
Add datadir path to gpsegconfig_dump at cdb dispatcher test

At commit 0cb79ba49c7c8106942e81be7aad0b2877f6f0a3 dumping datadir was added
support to include datadir in segment configuration dump. At the unit test
the gpsegconfig_dump was changed according to this commit.

This patch adds datadir path to each segment configuration at the
gpsegconfig_dump file.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/71817

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1452055

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1452056

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1452051

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1452053

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1452052

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1452054

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/71877

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1455641

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1455642

**Review by InnerLife0 — APPROVED** [review]

**Pull request merged**
