### PR TITLE
ADBDEV-4991: Fix resgroup_memory_limit test.

### PR DESCRIPTION
**Pull request by RekGRpth**
Fix resgroup_memory_limit test.

Upstream runs tests on resource groups in an environment with the default value
of statement_mem = 125MB, while on our CI we run the same tests in an
environment with an explicit statement_mem = 250MB. This patch corrects the
output of the resgroup_memory_limit test for such an environment.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1110796

**Comment by BenderArenadata** [comment]
Failed job Behave tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1110795

**Comment by swork12** [comment]
bender build

**Comment by swork12** [comment]
bender build

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1139295

**Comment by swork12** [comment]
bender build

**Comment by BenderArenadata** [comment]
Failed job Behave tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1141598

**Comment by KnightMurloc** [comment]
Can you remind me where "statement_mem = 250MB" is set and why we can't change the environment?

**Comment by RekGRpth** [comment]
> Can you remind me where "statement_mem = 250MB" is set and why we can't change the environment?

Our CI calls the make_cluster function, which sets this limit: https://github.com/arenadata/gpdb/blob/1710ca20c6de81dd533b3d40e3fe0c1e1544daa1/concourse/scripts/common.bash#L164

**Comment by KnightMurloc** [comment]
Maybe we can overwrite this value before running the tests?

**Comment by RekGRpth** [comment]
> Maybe we can overwrite this value before running the tests?

How?

**Comment by KnightMurloc** [comment]
As I understand it, we are now turning off ORCA for tests via an environment variable. Why can't we change this variable in the test launch scripts? Or does it have an effect only when creating a cluster?

**Comment by RekGRpth** [comment]
> As I understand it, we are now turning off ORCA for tests via an environment variable. Why can't we change this variable in the test launch scripts? Or does it have an effect only when creating a cluster?

Yes, this is installed when creating the cluster. https://github.com/arenadata/gpdb/blob/1710ca20c6de81dd533b3d40e3fe0c1e1544daa1/concourse/scripts/common.bash#L164-L167

**Comment by KnightMurloc** [comment]
>Yes, this is installed when creating the cluster. 

yes, but if we change the value after creating the cluster, will it have an effect?

**Comment by RekGRpth** [comment]
> if we change the value after creating the cluster, will it have an effect?

Yes, but where exactly?

**Comment by KnightMurloc** [comment]
in the CI scripts that run the tests?

**Comment by RekGRpth** [comment]
> in the CI scripts that run the tests?

There's no easy way to do this. We will then have to additionally perform gpconfig and restart the cluster.

**Comment by Stolb27** [comment]
> There's no easy way to do this. We will then have to additionally perform gpconfig and restart the cluster.

Is it for changing statement mem? Sure? What about setting over PGOPTIONS similar to altering optimizer GUC? Is there cons for such approach?

**Comment by RekGRpth** [comment]
> What about setting over PGOPTIONS similar to altering optimizer GUC?

Then we need to edit CI, not the code in the repository.

**Comment by KnightMurloc** [comment]
> Then we need to edit CI, not the code in the repository.

I think it will be better this way as we will get an environment closer to the upstream.

**Comment by RekGRpth** [comment]
> > Then we need to edit CI, not the code in the repository.
> 
> I think it will be better this way as we will get an environment closer to the upstream.

Upstream runs these tests completely differently: https://github.com/arenadata/gpdb/blob/1710ca20c6de81dd533b3d40e3fe0c1e1544daa1/concourse/scripts/ic_gpdb_resgroup.bash#L59-L78

**Comment by KnightMurloc** [comment]
I think that if it's not too difficult to change the environment, then it's better to change it than the test.

**Comment by RekGRpth** [comment]
> I think that if it's not too difficult to change the environment, then it's better to change it than the test.

Also, we may run tests like in https://github.com/arenadata/gpdb/pull/883

**Comment by swork12** [comment]
bender build

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1158643

**Comment by RekGRpth** [comment]
We made our environment for testing resource groups closer to the upstream.

**Pull request closed without merging**
