### PR TITLE
ADBDEV-1905 6.17.1 sync

### PR DESCRIPTION
**Pull request by deart2k**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by Stolb27** [comment]
GPORCA conflicts are caused by the mismatch of [our commit](https://github.com/arenadata/gpdb/commit/90afebcd9404a87ab1c4e95b17a6f6a2734b4d63) and [upstream backport](https://github.com/greenplum-db/gpdb/commit/af7c79b4f936b9824a7bba4e31017d6a51ebba75). Upstream backport contains only part of our changes. Moreover, we can't create a minidump for `AllSubqueryWithSubqueryInScalar` with the upstream version of the patch, because ORCA can't produce a valid plan:

```
test=#      EXPLAIN SELECT * FROM foo WHERE (SELECT a FROM foo limit 1) = ALL(SELECT b FROM bar);
LOG:  statement: EXPLAIN SELECT * FROM foo WHERE (SELECT a FROM foo limit 1) = ALL(SELECT b FROM bar);
LOG:  2021-07-23 03:19:50:933783 UTC,THD000,TRACE,"[OPT]: Number of plan alternatives: 12
",
2021-07-23 03:19:50:942197 UTC,THD000,ERROR,"DXL-to-PlStmt Translation: Attribute number 22661984 not found in project list",
LOG:  Pivotal Optimizer (GPORCA) failed to produce plan (unexpected)
```

We don't which query creates `AllSubqueryWithSubqueryInScalar.mdp` but it passes the test successfully.
After discussion with @darthunix, we decided to **revert the upstream patch** and open an issue about the problem.

**Comment by Stolb27** [comment]
https://github.com/arenadata/gpdb/pull/232/commits/69f0824e2e41a9154915c065800e9a7680601f2b implements new gpload test suite that requires pytest in the environment.

**Comment by Stolb27** [comment]
@maksm90, @darthunix, @leskin-in this PR is ready for review. Please, take a look.

**Review by darthunix — APPROVED** [review]
We have a series of potentially dangerous commits about fsync on startup (I wish we would not be in trouble one day because if them). It was also funny to see that we still have logical errors in [resource queues](https://github.com/arenadata/gpdb/pull/232/commits/3d4f5536ffd8dde44775a4acba323a6f33cebe84).

Thanks @Stolb27 for his bug fixes in a current release.

**Comment by Stolb27** [comment]
1. https://github.com/arenadata/gpdb/pull/232/commits/894d868ae8c483ce78d8424a3f5a8251b572b414 removes ORCA's usages for `prodataaccess` attributes
2. c99892a by @InnerLife0. We need to rebase and correct #219 after merging this one

**Review by Stolb27 — APPROVED** [review]

**Pull request merged**
