### PR TITLE
ADBDEV-2435 ADB 6.19.0 sync

### PR DESCRIPTION
**Pull request by deart2k**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by Stolb27** [comment]
There were conflicts caused by:

1. mismatches between our patch and fc39bc9
2. mismatches between eb9d1f0 and backported in #197 
3. 3fac07208d has made possible to produce plan by ORCA for query in subselect test
4. spaces in notin_optimzier modified in ebb691a affects our version of patch #170 (#182)

**Comment by Stolb27** [comment]
@maksm90, @InnerLife0. There are only known failures of behave tests. So this PR is ready for review.

**Review by InnerLife0 — APPROVED** [review]
Looked for resolved conflicts caused by my PR. Seems OK.
Others looks OK too.

**Review by maksm90 — APPROVED** [review]

**Review by Stolb27 — APPROVED** [review]
@deart2k, this PR is ready to merge. Then I'm going to merge our patches.

**Pull request merged**
