### PR TITLE
NOT FOR MERGE / PR FOR CI TESTS

### PR DESCRIPTION
**Pull request by swork12**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1238240

**Comment by BenderArenadata** [comment]
Failed job JIT tests with Postgres optimizer: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1238242

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1238241

**Comment by BenderArenadata** [comment]
Failed job JIT tests with ORCA: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1238243

**Comment by swork12** [comment]
bender build

**Pull request closed without merging**
