### PR TITLE
ADBDEV-5260: Remove a null pointer check for canonical_grpsets

### PR DESCRIPTION
**Pull request by bandetto**
Remove a null pointer check for canonical_grpsets

canonical_grpsets is asserted to be not-NULL before the affected condition.
Remove the redundant NULL check.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/67993

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1228652

**Review by RekGRpth — APPROVED** [review]

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1228646

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1228653

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68069

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1230211

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1230212

**Pull request merged**
