### PR TITLE
 ADBDEV-3999-1: ORCA generates incorrect plan with exists clause for partitioned table

### PR DESCRIPTION
**Pull request by RekGRpth**
ORCA generates incorrect plan with exists clause for partitioned table

For subqueries with EXISTS, the [first column is always selected](https://github.com/arenadata/gpdb/blob/bb5a6b85b52161d40aa081dc2c5ec9561eabdb65/src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp#L1302-L1304) by ORCA.
But if this column does not participate anywhere else in the query and is neither a system nor a distribution key, then it is not marked as used.
Therefore, [when translating to DXL, such a column is skipped](https://github.com/arenadata/gpdb/blob/6ed03a1d78ef8ab6560dc9a5b40a47cd75faaa75/src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp#L7573-L7585), and in a debug build, such a plan is generally not allowed!
On a release build, when a column is skipped, that column is not added to [table_descr](https://github.com/arenadata/gpdb/blob/6ed03a1d78ef8ab6560dc9a5b40a47cd75faaa75/src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp#L7605C3-L7605C14).
And therefore, its number is not inserted into the [m_colid_to_attno_map](https://github.com/arenadata/gpdb/blob/6ed03a1d78ef8ab6560dc9a5b40a47cd75faaa75/src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp#L4699) hashmap of the correspondence of the column number to the attribute number.
And now the attribute number [is not found](https://github.com/arenadata/gpdb/blob/6ed03a1d78ef8ab6560dc9a5b40a47cd75faaa75/src/backend/gpopt/translate/CMappingColIdVarPlStmt.cpp#L140) by the column number.
And so a variable with an [unknown](https://github.com/arenadata/gpdb/blob/6ed03a1d78ef8ab6560dc9a5b40a47cd75faaa75/src/backend/gpopt/translate/CMappingColIdVarPlStmt.cpp#L222-L226) attribute number is created.
Such a variable with an unknown attribute number is treated as a [whole-row](https://github.com/arenadata/gpdb/blob/6ed03a1d78ef8ab6560dc9a5b40a47cd75faaa75/src/backend/executor/execQual.c#L5391-L5399).
In this case, the oid of this variable does not correspond to the [composite type](https://github.com/arenadata/gpdb/blob/6ed03a1d78ef8ab6560dc9a5b40a47cd75faaa75/src/backend/utils/cache/typcache.c#L754-L758) and an error occurs.
The solution to the problem is return only used columns for all logical operators.

Reproduction on release build:
```sql
CREATE TABLE offers (
    id int,
    product int,
    date date
) DISTRIBUTED BY (id);

INSERT INTO offers SELECT 0, 0, '2023-01-01';

CREATE TABLE contacts (
    contact text,
    id int,
    date date
) DISTRIBUTED BY (id) PARTITION BY RANGE(date) (START (date '2023-01-01') INCLUSIVE END (date '2023-02-01') EXCLUSIVE EVERY (INTERVAL '1 month'));

INSERT INTO contacts SELECT '0', 0, '2023-01-01';

EXPLAIN (ANALYZE on, COSTS off, VERBOSE on)
SELECT id FROM offers WHERE EXISTS (
    SELECT id FROM contacts WHERE product = 0 OR contacts.id = offers.id
);

ERROR:  type text is not composite  (seg1 slice2 172.19.0.3:6435 pid=55051)
```
On a debug build, ORCA can't build a plan.
```sql
CTranslatorExprToDXL.cpp:7580: Failed assertion: !reqd_prop_plan->PcrsRequired()->FMember(colref)
LOG:  Pivotal Optimizer (GPORCA) failed to produce plan (unexpected)
```

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/57944

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/763392

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/763396

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/763393

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/763397

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/763390

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/763391

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/57954

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/764677

**Comment by BenderArenadata** [comment]
Failed job Behave tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/764675

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/58568

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795677

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795674

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795678

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795673

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795672

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/795671

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/58584

**Comment by RekGRpth** [comment]
This patch is broken by
```sql
EXPLAIN (ANALYZE off, COSTS off, VERBOSE on)
SELECT * FROM (values (1), (2)) a WHERE EXISTS (
    SELECT * FROM (values (3), (4)) as b
);
2023-11-17 12:44:59:687907 +05,THD000,ERROR,"../../../../../../src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h:1115: Failed assertion: __null != pcrInner
Stack trace:
1    0x0000000000f630b8 gpos::CErrorContext::Record + 178
2    0x0000000000f6402e gpos::CException::Raise + 256
3    0x0000000001231035 gpopt::CExpression* gpopt::CUtils::PexprLogicalApply + 209
4    0x000000000122ecf1 gpopt::CSubqueryHandler::FRemoveExistentialSubquery + 571
5    0x000000000122edcd gpopt::CSubqueryHandler::FRemoveExistsSubquery + 133
6    0x000000000122f3d4 gpopt::CSubqueryHandler::FProcessScalarOperator + 432
7    0x000000000122f56b gpopt::CSubqueryHandler::FProcess + 151
8    0x000000000128e499 gpopt::CXformSubqueryUnnest::PexprSubqueryUnnest + 325
9    0x000000000128e783 gpopt::CXformSubqueryUnnest::Transform + 69
10   0x000000000128e8c7 gpopt::CXformSubqueryUnnest::Transform + 291
11   0x00000000011b5467 gpopt::CGroupExpression::Transform + 857
12   0x00000000011d0f37 gpopt::CJobTransformation::EevtTransform + 199
13   0x00000000011d1498 gpopt::CJobStateMachine + 330
14   0x00000000011d1054 gpopt::CJobTransformation::FExecute + 110
15   0x00000000011d7779 gpopt::CScheduler::FExecute + 77
16   0x00000000011d717f gpopt::CScheduler::ExecuteJobs + 97
17   0x00000000011d7116 gpopt::CScheduler::Run + 50
18   0x00000000010ed141 gpopt::CEngine::Optimize + 853
19   0x00000000011a2fc4 gpopt::COptimizer::PexprOptimize + 84
20   0x00000000011a29da gpopt::COptimizer::PdxlnOptimize + 1244
21   0x00000000012f8422 COptTasks::OptimizeTask + 1358
22   0x0000000000f77bfd gpos::CTask::Execute + 171
23   0x0000000000f7a335 gpos::CWorker::Execute + 175
24   0x0000000000f76178 gpos::CAutoTaskProxy::Execute + 190
25   0x0000000000f7c2c4 gpos_exec + 755
26   0x00000000012f726a COptTasks::Execute + 192
27   0x00000000012f9039 COptTasks::GPOPTOptimizedPlan + 139
28   0x00000000012f9d7d CGPOptimizer::GPOPTOptimizedPlan + 73
29   0x00000000012fa32d GPOPTOptimizedPlan + 35
30   0x0000000000bf5e5d optimize_query + 464
31   0x0000000000bd8e33 standard_planner + 152
",
LOG:  Pivotal Optimizer (GPORCA) failed to produce plan (unexpected)
                  QUERY PLAN                  
----------------------------------------------
 Result
   Output: "*VALUES*".column1
   One-Time Filter: $0
   InitPlan 1 (returns $0)
     ->  Limit
           Output: "*VALUES*_1".column1
           ->  Values Scan on "*VALUES*_1"
                 Output: "*VALUES*_1".column1
   ->  Values Scan on "*VALUES*"
         Output: "*VALUES*".column1
 Optimizer: Postgres query optimizer
 Settings: optimizer=on
(12 rows)
```

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/796051

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/796052

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/796045

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/58620

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797360

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797550

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797595

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/58631

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797606

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797603

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797607

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797602

**Comment by BenderArenadata** [comment]
Failed job Behave tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797604

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797600

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/797601

**Pull request closed without merging**
