### PR TITLE
Sync 6.26.3 changes

### PR DESCRIPTION
**Pull request by Stolb27**
742bf6f, fc2aade conflict with 08d747e
6425610 conflicts with b72ff6b
5a10d0a conflicts with b72ff6b
93d4623 conflicts with cb1a87c
611ff8a, ebd310c, 55e1511 conflict with 9290a5c
9290a5c output need to be duplicated for power

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/66009

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1129867

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1129868

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1129857

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1129859

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1132009

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/66106

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1134741

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1134742

**Comment by Stolb27** [comment]
6.27.1 was already synced

**Pull request closed without merging**
