### PR TITLE
Remove redundant extern keywords

### PR DESCRIPTION
**Pull request by Ildangbaek**
Remove redundant extern keywords

It is written in the "6.2.2 Linkages of identifiers" chapter of C99 standard
(https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf): 
"If the declaration of an identifier for a function has no storage-class
specifier, its linkage is determined exactly as if it were declared with 
the storage-class specifier extern". The "6.9 External definitions" chapter
contains the following: "An external definition is an external declaration that
is also a definition of a function (other than an inline definition) or
an object". So the extern keyword is redundant in function definitions.

Greenplum specific code is changed only.

### CODE REVIEW

**Comment by andr-sokolov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Failed job Build ubuntu22 for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1909895

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/80214

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1909900

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1909899

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1909898

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1909902

**Comment by BenderArenadata** [comment]
Failed job Behave tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1909901

**Comment by andr-sokolov** [comment]
Are there any more redundant `extern` keywords? Add please PR description about why `extern` is redundant in this case

**Comment by Ildangbaek** [comment]
> Are there any more redundant `extern` keywords? Add please PR description about why `extern` is redundant in this case

Done.

**Comment by andr-sokolov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/82288

**Review by andr-sokolov — APPROVED** [review]

**Comment by andr-sokolov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/84224

**Pull request merged**
