### PR TITLE
ADBDEV-2967 6.21.1 sync

### PR DESCRIPTION
**Pull request by deart2k**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by Stolb27** [comment]
Interesting commits:

1. https://github.com/arenadata/gpdb/pull/372/commits/1c3c4aeddc7e154a2387740429f88dfa47fd95ce - ~~possibly fixes https://tracker.yandex.ru/ADBDEV-1045~~ It was fixed a long time ago by https://github.com/greenplum-db/gpdb/pull/11692
2. https://github.com/arenadata/gpdb/pull/372/commits/48d323ea24114614643d8f1425ab296826563ea7 - backport Postgres patch to fix mirror replication
3. https://github.com/arenadata/gpdb/pull/372/commits/c9e795b7979904f56586495bd9dc3e4357a41ad6 describes reasons of massive WAL writing on select from heap-table
4. https://github.com/arenadata/gpdb/pull/372/commits/cdd532fe03768cdba22b45852f7c33008ef431b6 ~~should solve https://tracker.yandex.ru/ADBDEV-2629~~ This fix implement only earlier fallback to postgres.

I'm going to revert https://github.com/arenadata/gpdb/commit/ad90ace3aa4c13220aec17821985b9099f1f04dc to avoid conflicts with https://github.com/arenadata/gpdb/pull/372/commits/62b58c7634050be5c947e7151592725bd5fc82be, and 0aa9505cf0283e72730cbf550644b97990efb342 for the similar reasons.

Also, there are conflicts between upstream a39ff3d53fcd831a6efbc9d2ebf55706ebadbfda and our 18fec6cb70051af51a421892d9d2663a3f0ee4a9, introduced during merge #306. Motivation was described [here](https://github.com/greenplum-db/gpdb/pull/12976#discussion_r811598082).

**Comment by Stolb27** [comment]
Changes of rpt regression test are caused by unaccepted yet patches:

* https://github.com/arenadata/gpdb/commit/3cfbbc20bf296d61961db9eaa21c9cf07011817e corrected Subquery Scan cost
* https://github.com/arenadata/gpdb/commit/0b07601939f4e888a5fb6b177e60e2a412878ed9 fixed constants representation

**Comment by Stolb27** [comment]
This patch is ready for review.

**Comment by InnerLife0** [comment]
> Also, there are conflicts between upstream [a39ff3d](https://github.com/arenadata/gpdb/commit/a39ff3d53fcd831a6efbc9d2ebf55706ebadbfda) and our [18fec6c](https://github.com/arenadata/gpdb/commit/18fec6cb70051af51a421892d9d2663a3f0ee4a9), introduced during merge #306. Motivation was described [here](https://github.com/greenplum-db/gpdb/pull/12976#discussion_r811598082).

Yeah, this one incompletely copied by pivotal developer from my patch without any reference.

**Review by InnerLife0 — APPROVED** [review]

**Review by maksm90 — APPROVED** [review]

**Pull request merged**
