### PR TITLE
6.27.1 sync

### PR DESCRIPTION
**Pull request by red1452**
## Conflicts:

New commit:
- Handle ICProxy addresses during gpexpand (https://github.com/greenplum-db/gpdb/pull/17009) commit 3b0526d5ebcb87927f68c842c6f49546d4b30a37

Reverted:
- Fix inconsistency between the format of queries_now.dat and the queries_now_fast external table (https://github.com/arenadata/gpdb/pull/636) commit 742bf6f9389dce4c449fc9bcb26b06698116d84b
- Add more locales to docker image and add tests (#481) commit a3a94c54dd5d9f8797541860250735c7fcb08348

## 

New commit:
- fix panic when concurrent update with before row update trigger. commit fe2aa2fe48e97a6491fec23e6259b053b52d6cc8

Reverted:
- ADBDEV-3675: trigger: Use junkFilter from relinfo instead of estate (#526) commit e26da713783d9a71b179302f5e40e671fe139c27

## 

New commit:
- Keep partition child lock until end of select commit 4ac7227e93dc294b3527557ae7cb5185a734bdd4

Reverted:
- Add support for target cols with functional dependency on grouping ones to ORCA (#746) commit 89430f7fd3869ba2bd42c1698bb4bf824d87e067
- Keep locks on child partitions until end of SELECT (#928) commit c336098df9901412381f23282473ffbdcedd46ec
- On DDL operation keep the lock on partitions until end of transaction (#295) commit 74fb2b3f1990ba92606aead85f37bad99206b10b
- Keep partition child lock until end of select (#897) commit a8975320bd5838c0fb731d52d4154ae297f44ab1

##

New commit:
- [6X Backport] Fix issue with WAL archiving in standby. commit 5e3e0f71ec371eac9b3a070bcb458e7fd40099b3

Reverted:
- Make postmaster restart archiver soon after it dies, even during recovery. (#261) commit 71a40620bf5608db9031b528a811a5376312df63
- Add archive_mode='always' option. (#261) commit fa759d1bf70c020f884f05cf7ae15c6b9b47b4b1
- Fix WAL recycling on standbys depending on archive_mode (#877) commit 62ab24ac5187a412280c85ea2cedec274804e315

##

New commit:
- Fix Orca to not generate unnecessary slices for plans with Subplans commit 6b7a83056a7af01ff6aaf2cbb4e2095cfb8d2610

Reverted:
- ORCA: Improve CTE validation only for affected slice (#550) commit 54ee0580a6c4eae26f2650981f65b33f5f41d54c

##

New commit:
- Add multi-thread compression for gpfdist in gpdb6 (#16914) commit 54a7f132ae7557c4f19cd3d6cebd0fc46dac89ed

Reverted:
- Implement default transformation flags for gpfdist (#934) commit 2f6e3ef9af0c74b5297a5577566fbf0d6b8c58e4

##

New commit:
- Avoid replay dtx info in checkpoint for newly expanded segments (#17408) commit ab5a612bfdc355ad2d601860dfb70a47778c8dd7

Reverted:
- gpexpand: skip expanded/broken tables when redistributing (#887) commit cfb97d174c3e3b7987771a5c95b750f6a8c7febb

##

New commit:
- Reject substituting extension schemas or owners matching ["$'\]. commit 482d4e839d519dcfde9cddf03807787d9d91d015

Reverted:
- Avoid linking AO aux tables to extension (#930) commit 10ec9c7ae00475f0db823d53a038b3768b679d63

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1439627

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1439626

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1444386

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1444387

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1444428

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1446450

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1446449

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1451028

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1451027

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1451951

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1451952

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1455506

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1455507

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1455875

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1455876

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/71903

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1456814

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1456816

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1456811

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1456810

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1456812

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1456813

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/71924

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458215

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458216

**Comment by BenderArenadata** [comment]
Failed job Behave tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458218

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458211

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458212

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458213

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458214

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/71932

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458644

**Comment by BenderArenadata** [comment]
Failed job Orca unittests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458645

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458639

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458641

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458638

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1458642

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/71997

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1461660

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1461659

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1461661

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1461662

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/72032

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1463921

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1463922

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1463923

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1463924

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/72157

**Review by InnerLife0 — DISMISSED** [review]

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1469567

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/72189

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1471305

**Review by Stolb27 — APPROVED** [review]

**Pull request merged**
