### PR TITLE
5.28.7 sync

### PR DESCRIPTION
**Pull request by deart2k**

### CODE REVIEW

**Review by maksm90 — APPROVED** [review]

**Comment by maksm90** [comment]
@darthunix please check conflicts that seems to regard your fix of resgroup waiting.

**Comment by darthunix** [comment]
@maksm90 I suppose @Stolb27 plans to revert a conflict commit with https://github.com/arenadata/gpdb/pull/174 and use upstream version.

**Review by darthunix — APPROVED** [review]
https://github.com/greenplum-db/gpdb/pull/11688 changes recommended kernel parameters `shmmax` and `shmall`. Interesting, that we don't set these parameters in our bundle (`adb-5.x-dev` branch).

**Comment by Stolb27** [comment]
> @darthunix please check conflicts that seems to regard your fix of resgroup waiting.

@maksm90 , done

**Comment by Stolb27** [comment]
> [greenplum-db#11688](https://github.com/greenplum-db/gpdb/pull/11688) changes recommended kernel parameters `shmmax` and `shmall`. Interesting, that we don't set these parameters in our bundle (`adb-5.x-dev` branch).

I've mentioned this commit in https://arenadata.atlassian.net/browse/ADBDEV-604

**Review by maksm90 — APPROVED** [review]

**Comment by maksm90** [comment]
Hmm, two test cases (`test__gp_malloc_and_free__basic_tests` and `test__gp_realloc__basic_tests`) have failed

**Comment by leskin-in** [comment]
Note https://github.com/greenplum-db/gpdb/pull/11720, which is included in this PR: it reveals a bit of GPCC logic. [This](https://github.com/greenplum-db/gpdb/pull/11720/files#diff-eca689b02874d585dbe0547b5b5af6e723a88247c89b662fa0f601f3d363d4f5R1818) may imply that GPCC analyses statements, *not only* (or just *not*) the plan tree.

**Review by leskin-in — APPROVED** [review]

**Comment by darthunix** [comment]
>Note greenplum-db#11720, which is included in this PR: it reveals a bit of GPCC logic. This may imply that GPCC analyses statements, not only (or just not) the plan tree.

@leskin-in  it seems to be GPDB 5X specific patch and ADB-CC works only with 6X at the moment (I hope it would never mess with 5X)

**Review by Stolb27 — APPROVED** [review]

**Pull request merged**
