### PR TITLE
ADBDEV-6756: [6X] Migrate ADBC dependencies to the base image

### PR DESCRIPTION
**Pull request by bandetto**
[6X] Migrate ADBC dependencies to the base image

The ADCC extension's scripts are split in different files due to differences in
dependencies across Linux distributions. This patch adds required dependencies
to the base Ubuntu image.

* Move adb-python bin/ directory to a reusable variable.
* Add protobuf-compiler to apt packages and protobuf==3.20.0 python module to
  base image for Ubuntu.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/86562

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/86727

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/87020

**Review by red1452 — COMMENTED** [review]
When I try to run adcc-extension's tests (I removed lines from script with installing protobuf-compiler and protobuf), I get error:
```
make[1]: Leaving directory '/home/gpadmin/adcc/adcc-extension/unit_tests'
test/prepare_database_for_tests.sh
  File "/usr/local/greenplum-db-devel/bin/gpconfig", line 189
    print "[name: %s] [unit: %s] [context: %s] [vartype: %s] [min_val: %s] [max_val: %s]" % (
          ^
SyntaxError: invalid syntax
make: *** [Makefile:146: database_prepared_for_tests] Error 1
make: Leaving directory '/home/gpadmin/adcc/adcc-extension'
++ cat adcc/adcc-extension/regression.diffs
cat: adcc/adcc-extension/regression.diffs: No such file or directory
```

**Comment by bandetto** [comment]
> When I try to run adcc-extension's tests (I removed lines from script with installing protobuf-compiler and protobuf), I get error

Yeah, `test/test_in_docker_u22.sh` contains the following line, which is causing this error:
```
export PATH=/opt/adb6-python3.9/bin/:$PATH
```
After this patch, `/opt/adb6-python3.9/bin/` now has a `python` executable, which will replace `python2` if is in `PATH`. All binaries except `python` are already symlinked to `/usr/local/bin/`. You can use the script added in the MR of ADCC-4880 on Gitlab to test these changes.

The other way to fix it is to change `pip3`'s shebang inside `adb6-python` package, but it's even more dirty and it seems that CI team does not want to touch this.

**Review by red1452 — DISMISSED** [review]
All tests passed on the ADCC-4880-2 branch with Docker image from this PR.

**Review by silent-observer — DISMISSED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/87598

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/87617

**Comment by silent-observer** [comment]
When run on ADCC-4880-2 with
```
docker run --rm -it --privileged --sysctl 'kernel.sem=500 1024000 200 4096' -v $PWD:/home/gpadmin/adcc hub.adsw.io/library/gpdb6_u22:ADBDEV-6756 adcc/adcc-extension/test/test_in_docker_u22.sh
```
some tests fail (`node_status`, `polymorphism`, `sqlid`, `hooks_manipulation`, `query_band`). Is this expected?

**Comment by bandetto** [comment]
> ```
> docker run --rm -it --privileged --sysctl 'kernel.sem=500 1024000 200 4096' -v $PWD:/home/gpadmin/adcc hub.adsw.io/library/gpdb6_u22:ADBDEV-6756 adcc/adcc-extension/test/test_in_docker_u22.sh
> ```

You skipped `--sysctl 'net.unix.max_dgram_qlen=4096'` in the command. I reran the tests and they worked ok.

**Review by red1452 — DISMISSED** [review]

**Review by silent-observer — DISMISSED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/87715

**Review by silent-observer — APPROVED** [review]

**Pull request merged**
