### PR TITLE
Fix FNullRejecting() error while trying to process zero-placed predicate

### PR DESCRIPTION
**Pull request by InnerLife0**
When trying to do NULL rejection over zero-placed predicate, e.g. any strict function with zero arguments, we may pass NULL children array from EberEvaluate() to underlying Eber() functions. This may lead to errors, such as assertion error at EberNullOnAnyNullChild() function which used by many subclasses. As underlying Eber() functions doesn't perform any NULL check, we need to pass an empty array to them in case we working with zero-placed predicate.
Another option was to return EberAny from EberEvaluate() in case we dealing with zero arity, but there is underlying CScalarConst::Eber() function which should be called and which do it's stuff ignoring incoming argument at all. Here I decided to keep current solution as it's clean.

A little highlighting of function folding. If you'll remove topmost select from any of new tests, you'll not get an error because strict function will be folded, and thus, became Const. Starting from 4cf47434a35df73dd456b6648c5f40ee377b5845 such functions under topmost select not folded, because such select has no parse->rtable. At the other hand, Postgres planner, on which ORCA fell back before current patch, can do folding because of separate calls to eval_const_expressions() from subplans.

### CODE REVIEW

**Comment by maksm90** [comment]
> When trying to do NULL rejection over zero-placed predicate, e.g., ...

IMO the term `zero-placed predicate` is kind of confusing here. I'd rename it to `predicate containing function without arguments`.

> Another option was to return EberAny from EberEvaluate() in case we dealing with zero arity, but there is underlying CScalarConst::Eber() function which should be called and which do it's stuff ignoring incoming argument at all. Here I decided to keep current solution as it's clean.

Why not to extend `CScalarFunc::Eber()` function to allow NULL argument, e.g. smth like
```C
--- a/src/backend/gporca/libgpopt/src/operators/CScalarFunc.cpp
+++ b/src/backend/gporca/libgpopt/src/operators/CScalarFunc.cpp
@@ -241,7 +241,7 @@ CScalarFunc::OsPrint(IOstream &os) const
 CScalar::EBoolEvalResult
 CScalarFunc::Eber(ULongPtrArray *pdrgpulChildren) const
 {
-    if (m_returns_null_on_null_input)
+    if (pdrgpulChildren && m_returns_null_on_null_input)
     {
         return EberNullOnAnyNullChild(pdrgpulChildren);
     }
```
?
It makes this function more universal for other callers who also might pass null value. Also it's not necessary to impose precondition in form of assert check about not-null argument. If you will decide to stay your own variant, please add this precondition check into `CScalarFunc::Eber()`.

> A little highlighting of function folding. If you'll remove topmost select from any of new tests, you'll not get an error because strict function will be folded, and thus, became Cons.

Despite of in referred commit https://github.com/arenadata/gpdb/commit/4cf47434a35df73dd456b6648c5f40ee377b5845 the term `function folding` is used, IMO it's bad choice and the `function pre-evaluation` will be better. The term `folding` might be applicable to expressions which contain such pre-evaluated function.

> .. such functions under topmost select not folded, because such select has no parse->rtable.

I'd rewrite to `such functions are not pre-evaluated in case of multi-level query when outermost query text doesn't have any table references`.

**Comment by maksm90** [comment]
In general, in PR description I'd like to see:

- the faulty case
- rough upper level description of failure reason
- detailed description with links to source code
- the note about function pre-evaluation logic as explanation why we don't observe the error in regular single level query

**Comment by InnerLife0** [comment]
> IMO the term `zero-placed predicate` is kind of confusing here. I'd rename it to `predicate containing function without arguments`.

I choose it, because It's short and [known](https://en.wikipedia.org/wiki/Predicate_(mathematical_logic)).

> Why not to extend `CScalarFunc::Eber()` function to allow NULL argument, e.g. smth like

You mean check and possibly change all 10 `Eber()` functions? `CScalarFunc::Eber()` used only in our example. If you want to do fix in that way, then, in general, you should check and, if necessary, change all the `Eber()` functions.

> Despite of in referred commit [4cf4743](https://github.com/arenadata/gpdb/commit/4cf47434a35df73dd456b6648c5f40ee377b5845) the term `function folding` is used, IMO it's bad choice and the `function pre-evaluation` will be better. The term `folding` might be applicable to expressions which contain such pre-evaluated function.

I can't judge which choice is bad, but the current choice refers us to a function `fold_constants()`, which is the entry point for ORCA to do all of this stuff described.
Or I didn't understand you right.
Anyway, want to hear @Stolb27 opinion here.

**Comment by InnerLife0** [comment]
> * the faulty case

The nature of the fault described in the first paragraph. The detailed case is available as new regression test.
Or did you mean something else?

> * rough upper level description of failure reason
> * detailed description with links to source code

Can't understand here. Do you want two separate descriptions here? If yes, why?

> * the note about function pre-evaluation logic as explanation why we don't observe the error in regular single level query

The current note explains exactly such case. Or you probably mean the case when we not fall on same level query, but without join?

**Comment by maksm90** [comment]
> > IMO the term `zero-placed predicate` is kind of confusing here. I'd rename it to `predicate containing function without arguments`.
> 
> I choose it, because It's short and [known](https://en.wikipedia.org/wiki/Predicate_(mathematical_logic)).

OK, accepted.

> > Why not to extend `CScalarFunc::Eber()` function to allow NULL argument, e.g. smth like
> 
> You mean check and possibly change all 10 `Eber()` functions? `CScalarFunc::Eber()` used only in our example. If you want to do fix in that way, then, in general, you should check and, if necessary, change all the `Eber()` functions.

Just the opposite: in current version implicitly imposing precondition that argument have not be null we have to propagate such restriction on parent polymorphic version `Scalar::Eber()` and all child implementations. But... given that almost all child implementations someway call internal functions that expose not null precondition without any checks then we also have to fix in all these places or specify assert that null argument is impossible by definition.

> `CScalarFunc::Eber()` used only in our example

It might be called somewhere later without thought that argument must not be null if we don't specify this explicitly. The body of `CScalarFunc::Eber()` is already looks buggy because it directly calls `CScalar::EberNullOnAnyNullChild()` with restricted assumption concerning incoming argument relying that somewhere on upper level of call stack someone have accounted such restriction.
 
> the current choice refers us to a function `fold_constants()`, which is the entry point for ORCA to do all of this stuff described.

The `fold_constants()` function is about folding of  **constant expression**, not functions.

**Comment by maksm90** [comment]
> > * the faulty case
> 
> The nature of the fault described in the first paragraph. The detailed case is available as new regression test. Or did you mean something else?

It's ugly to search simple reproducible case in tests.

> > * rough upper level description of failure reason
> > * detailed description with links to source code
> 
> Can't understand here. Do you want two separate descriptions here? If yes, why?

_rough upper level_ description and _detailed_ one are different by nature. It's all to simplify the dive into task problem and implementation choice.

> The current note explains exactly such case. Or you probably mean the case when we not fall on same level query, but without join?

In current point I haven't any objections. I have posted it to expose overall sketch of PR description

**Comment by InnerLife0** [comment]
> Just the opposite: in current version implicitly imposing precondition that argument have not be null we have to propagate such restriction on parent polymorphic version `Scalar::Eber()` and all child implementations. But... given that almost all child implementations someway call internal functions that expose not null precondition without any checks then we also have to fix in all these places or specify assert that null argument is impossible by definition.

Can't understand what's the opposite. If I understand you right, you speaking about rewriting of all `Eber()` implementations, which I mentioned.
If I'm not right, please correct me, because it's hard to read and understand.
If I'm right, do you think this PR is the right place to change all of this?

> The `fold_constants()` function is about folding of **constant expression**, not functions.

[No](https://github.com/arenadata/gpdb/blob/d4534e08c27ede9b572ecfcf0f167518bf562ff4/src/backend/optimizer/util/clauses.c#L2895). But sometimes we may talk it's about folding **to** constant expression.
```
#0  makeConst (consttype=22057, consttypmod=-1859273304, constcollid=22057, constlen=-1981551752, constvalue=94736407065536, constisnull=5 '\005', 
    constbyval=96 '`') at makefuncs.c:303
#1  0x0000562989548b84 in evaluate_expr (expr=0x56299141d1b0, result_type=1184, result_typmod=-1, result_collation=0) at clauses.c:5108
#2  0x0000562989547dde in evaluate_function (funcid=1299, result_type=1184, result_typmod=-1, result_collid=0, input_collid=0, args=0x0, 
    funcvariadic=0 '\000', func_tuple=0x7ffa757cfaf0, context=0x7ffc99936d30) at clauses.c:4629
#3  0x00005629895470e8 in simplify_function (funcid=1299, result_type=1184, result_typmod=-1, result_collid=0, input_collid=0, 
    args_p=0x7ffc99935a40, funcvariadic=0 '\000', process_args=1 '\001', allow_non_const=1 '\001', context=0x7ffc99936d30) at clauses.c:4228
#4  0x0000562989544858 in eval_const_expressions_mutator (node=0x5629913f13b8, context=0x7ffc99936d30) at clauses.c:2847
#5  0x0000562989464058 in expression_tree_mutator (node=0x5629913f12d8, mutator=0x5629895443aa <eval_const_expressions_mutator>, 
    context=0x7ffc99936d30) at nodeFuncs.c:2768
#6  0x00005629895470ac in simplify_function (funcid=2521, result_type=16, result_typmod=-1, result_collid=0, input_collid=0, 
    args_p=0x7ffc99936220, funcvariadic=0 '\000', process_args=1 '\001', allow_non_const=1 '\001', context=0x7ffc99936d30) at clauses.c:4219
#7  0x00005629895449cc in eval_const_expressions_mutator (node=0x5629913f1280, context=0x7ffc99936d30) at clauses.c:2895
#8  0x0000562989464130 in expression_tree_mutator (node=0x5629913f0fc0, mutator=0x5629895443aa <eval_const_expressions_mutator>, 
    context=0x7ffc99936d30) at nodeFuncs.c:2781
#9  0x0000562989546a8e in eval_const_expressions_mutator (node=0x5629913f0fc0, context=0x7ffc99936d30) at clauses.c:3881
#10 0x00005629894648ee in query_tree_mutator (query=0x56299141cc68, mutator=0x5629895443aa <eval_const_expressions_mutator>, 
    context=0x7ffc99936d30, flags=0) at nodeFuncs.c:2978
#11 0x0000562989464dd5 in query_or_expression_tree_mutator (node=0x5629913f0190, mutator=0x5629895443aa <eval_const_expressions_mutator>, 
    context=0x7ffc99936d30, flags=0) at nodeFuncs.c:3098
#12 0x0000562989544059 in fold_constants (root=0x5629913f0420, q=0x5629913f0190, boundParams=0x0, max_size=102400) at clauses.c:2551
```

**Comment by InnerLife0** [comment]
> It's ugly to search simple reproducible case in tests.

Want to check am I missed something, but from what time this became _ugly_? If that's true and we can't get full test case from regression even for such small PR, then we should start to modify much of our existing PRs.

~~I noticed how incorrectly you use some epithets in this PR.~~

> _rough upper level_ description and _detailed_ one are different by nature. It's all to simplify the dive into task problem and implementation choice.

Could you give me a link to the rules we suddenly started to follow? Or a link to your own PR for a reference, where you divide such descriptions, so I can watch and learn how to correctly distinguish rough and detailed descriptions?

But of course, it's just better to say what's wrong with the current one. In my opinion, it's not long or hard to dive.

> In current point I haven't any objections. I have posted it to expose overall sketch of PR description

OK. I always treated "I would like to" as "I will happy to", which assumes that all points below explained something you personally already miss in PR. It seems I was wrong, right?

**Comment by maksm90** [comment]
> Can't understand what's the opposite. If I understand you right, you speaking about rewriting of all Eber() implementations, which I mentioned.
If I'm not right, please correct me, because it's hard to read and understand.

Leaving your patch unchanged we have to rewrite all `Eber()`s too because we implicitly assume not null precondition for `CScalarFunc::Eber()` and to support **substitution principle** for polymorphic `Eber()` call in subtypes we have to propagate this precondition to all `Eber()` implementations (see point about preconditions in [Liskov's principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle#Principle)). In your patch by initiating argument `pdrgpulChildren` by empty array you implicitly satisfy this precondition on caller side: to `Eber()` implementations that normally work with null argument we disallow to pass null value, instead we pass empty array.

>  If I'm right, do you think this PR is the right place to change all of this?

It depends... If we make fast patch then your fix is enough, if we want to fix thing fundamentally to capture adjacent cases then fix have to propagate to other `Eber()`s.

>> The fold_constants() function is about folding of constant expression, not functions.

> [No](https://github.com/arenadata/gpdb/blob/d4534e08c27ede9b572ecfcf0f167518bf562ff4/src/backend/optimizer/util/clauses.c#L2895).

In the link above as well as in the body of `simplify_function()` I haven't seen any note about "function folding". Opposite, I found multiple occurrences of "constant folding" term that implies folding of expression containing constants.

**Comment by maksm90** [comment]
> Want to check am I missed something, but from what time this became ugly? If that's true and we can't get full test case from regression even for such small PR, then we should start to modify much of our existing PRs.
> Could you give me a link to the rules we suddenly started to follow? Or a link to your own PR for a reference, where you divide such descriptions, so I can watch and learn how to correctly distinguish rough and detailed descriptions?

My point about PR description is the wish, not rule or some directive. It's of course subjective but I suppose that my opinion will share some other peers. After all, there is nothing wrong if you expand your PR description using these and from others subjective critical points.

> But of course, it's just better to say what's wrong with the current one.

Nothing wrong, all my points above are subjective recommendations.

> In my opinion, it's not long or hard to dive.

It's so for someone who is in the context of problem and implementation details. I'd like to simplify the dive for ones who is in other side.

**Comment by InnerLife0** [comment]
> see point about preconditions in [Liskov's principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle#Principle)

I think you trying to apply LSP to the wrong part of code. All `Eber()`'s from sub-classes already satisfies LSP without any changes. They have the same declaration and none of sub-classes can do it stricter (possibly, you can't even compile something like this). And it's OK for sub-class to have an Assert, directly throw an exception or keep working if it needs so. Why? Because at the level of implementation we not dealing with pre- or even postconditions, we deal with something between (let's say conditions, if you want). And it's a very common case in OOP practice.

If you really want to change something on precondition level, then you probably want to use something like [this](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ri-nullptr), but it seems GSL or something similar not used in ORCA for a reason.

Back to code, I think it's pretty enough to add somewhere a comment, which will explain already implicitly existed contract of not-NULL `pdrgpulChildren`.

**Review by Stolb27 — DISMISSED** [review]
> It's ugly to search simple reproducible case in tests.

I think it's enough to have a text description when a test case is provided.

> It depends... If we make fast patch then your fix is enough, if we want to fix thing fundamentally to capture adjacent cases then fix have to propagate to other Eber()s.

It's the fast patch to solve the customer problem. Let's leave refactoring for a separate task or maybe for discussion with the community.

**Comment by maksm90** [comment]
> All Eber()'s from sub-classes already satisfies LSP without any changes. They have the same declaration and none of sub-classes can do it stricter (possibly, you can't even compile something like this).

Disagree about strictness. For example, it's OK for parent class's `CScalar::Eber()` to treat zero argument as null value or empty array while `CScalarFunc::Eber()` just allows the second option.

> And it's OK for sub-class to have an Assert, directly throw an exception or keep working if it needs so. Why? Because at the level of implementation we not dealing with pre- or even postconditions, we deal with something between (let's say conditions, if you want).

Disagree, asserts around arguments at the beginning of routine body as well as even restriction comments in function specification might be considered as precondition.

**Comment by InnerLife0** [comment]
> Disagree about strictness. For example, it's OK for parent class's `CScalar::Eber()` to treat zero argument as null value or empty array while `CScalarFunc::Eber()` just allows the second option.

I think you again mix preconditions with implementation code.

> Disagree, asserts around arguments at the beginning of routine body as well as even restriction comments in function specification might be considered as precondition.

Asserts are the part of implementation.
As for comments, yes, they partially can be treated as preconditions.

**Pull request merged**
