### PR TITLE
ADBDEV-5310: Revert merge commit

### PR DESCRIPTION
**Pull request by mos65o2**
Revert merge commit ADBDEV-5310 branch

  Revert fea5f63 due to incorrect merge type and not enough interviewers.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/82910

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/82920

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/82967

**Comment by RekGRpth** [comment]
I think this patch should consist of three commits: the first one is a revert, and the other two are the commits that were in the previous patch. The easiest way now is to cherry-pick them into this branch and that's it.

**Comment by mos65o2** [comment]
Revert only. Did you see the commit message? Are you satisfied?

**Review by RekGRpth — APPROVED** [review]

**Pull request merged**
