### PR TITLE
ADBDEV-6214: Fix gpexpand error if partitioned table is spread across multiple schemas

### PR DESCRIPTION
**Pull request by silent-observer**
Fix gpexpand error if partitioned table is spread across multiple schemas

If a partitioned table belongs to one schema and its partitions to another
schema, gpexpand would fail with "relation does not exist" error. This patch
fixes it by changing gpexpand's SQL query to use partition's schema instead of
parent's schema. Also added a behave test for this case.

Co-authored-by: Artem Vershinin <vav@arenadata.io>
Co-authored-by: Anton Vasiliev <a.vasiliev@arenadata.io>

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1853534

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/79205

**Review by red1452 — APPROVED** [review]

**Comment by dkovalev1** [comment]
The test has passed on my machine even if I revert the change to gpMgmt/bin/gpexpand locally. How is it possible?

Upd: That was because I have not performed make install which is needed for gpexpand as well. It works.

**Review by dkovalev1 — APPROVED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/79855

**Pull request merged**
