### PR TITLE
DONT MERGE / CI-2764 log test

### PR DESCRIPTION
**Pull request by swork12**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1118999

**Comment by swork12** [comment]
bender build

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1119282

**Comment by swork12** [comment]
bender build

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1134294

**Comment by Stolb27** [comment]
CI-2764 marked as done

**Comment by swork12** [comment]
bender build

**Comment by swork12** [comment]
Tested changes for CI-2796.

**Pull request closed without merging**
