### PR TITLE
ADBDEV-3075 6.22.0 sync

### PR DESCRIPTION
**Pull request by deart2k**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by Stolb27** [comment]
https://github.com/arenadata/gpdb/commit/6ab1120498a70e215a64a1ab1b6450f65dd1fe96 was reverted in favor of https://github.com/greenplum-db/gpdb/commit/4b6c079bc3aed35b2f161c377e208185f9310a69

**Comment by Stolb27** [comment]
https://github.com/arenadata/gpdb/pull/392/commits/b7c14cbfeb2ea6fb18a1c0050e0775ad0cf7ecdd implements changes that are unsupported by gcc 4.8.5:

```
-bash-4.2$ cat 1.c 
#if __has_include(<stdio.h>)
#include <stdio.h>
#endif

int main() {
    printf("Hello!");
}
-bash-4.2$ gcc 1.c 
1.c:1:18: error: missing binary operator before token "("
 #if __has_include(<stdio.h>)
                  ^
1.c: In function ‘main’:
1.c:6:5: warning: incompatible implicit declaration of built-in function ‘printf’ [enabled by default]
     printf("Hello!");
     ^
-bash-4.2$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
```

GCC 5 is required at least: https://gcc.gnu.org/gcc-5/changes.html

**Comment by Stolb27** [comment]
I've opened a separate [ticket](https://tracker.yandex.ru/ADBDEV-3097) for bug in the vacuum index implementation ([c7d99d9](https://github.com/arenadata/gpdb/pull/392/commits/c7d99d911fd2f813ca1661155aa973a3366ac165))

**Comment by Stolb27** [comment]
312cdb7258df466dc87fdf40948141aa768c9905 contains changes in the platform specific subselect_gp test. I'm going to modify test output for ppc64le.

**Review by andr-sokolov — APPROVED** [review]

**Review by InnerLife0 — APPROVED** [review]

**Review by maksm90 — APPROVED** [review]
There are two things that is interesting to note:
- extension and doc entry allowing to monitor subtransaction xid overflow: https://github.com/greenplum-db/gpdb/pull/13614 and https://github.com/greenplum-db/gpdb/pull/13943 . This would be helpful for postgres maintainability. 
- GUC to disable ORCA planning for queries with replicated tables https://github.com/greenplum-db/gpdb/pull/13764

**Review by Stolb27 — APPROVED** [review]

**Pull request merged**
