### PR TITLE
CI-1179 Run adb tests on ppc platform

### PR DESCRIPTION
**Pull request by julya935**
Behave tests used to fail because of pip installation. While installing allure-behave==2.4.0 the following error occurred: Failed to establish a new connection: [Errno -2] Name or service not known. Adding this package to Dockerfile solved this problem.

### CODE REVIEW

**Review by Maunty — DISMISSED** [review]

**Comment by Stolb27** [comment]
@julya935, hello, can you provide more details on why pip module installation is not enough in
https://github.com/arenadata/gpdb/blob/823674f5157e5b601e37184f5d66b28317d68963/arenadata/scripts/behave_gpdb.bash#L47? Maybe we can move all dependencies to docker image?

**Comment by julya935** [comment]
> @julya935, hello, can you provide more details on why pip module installation is not enough in
> 
> https://github.com/arenadata/gpdb/blob/823674f5157e5b601e37184f5d66b28317d68963/arenadata/scripts/behave_gpdb.bash#L47
> 
> ? Maybe we can move all dependencies to docker image?

@Stolb27 When I ran behave tests on power they would fail. The problem was with installation of this package. Here's the example https://ci.arenadata.io/blue/rest/organizations/jenkins/pipelines/gpdb_ppc64le/branches/PR-190/runs/31/nodes/171/steps/436/log/?start=0 
 And same error would occur several times in different places each build

**Comment by Stolb27** [comment]
> When I ran behave tests on power they would fail. The problem was with installation of this package. Here's the example

@julya935, Are you about this fail:

```
Collecting allure-behave==2.4.0
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c6975cdb50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c6976f2750>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
1 feature passed, 0 failed, 22 skipped
10 scenarios passed, 0 failed, 424 skipped
93 steps passed, 0 failed, 5147 skipped, 0 undefined
Took 12m33.163s

real	12m41.526s
user	1m54.597s
sys	0m42.935s
+ status=0
+ docker-compose -p gpmovemirrors_demo -f arenadata/docker-compose.yaml --env-file arenadata/.env down -v
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c69758c110>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
Stopping gpmovemirrors_demo_sdw1_1 ... 
Stopping gpmovemirrors_demo_sdw3_1 ... 
Stopping gpmovemirrors_demo_mdw_1  ... 
Stopping gpmovemirrors_demo_sdw2_1 ... 
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c69758c2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c69758c490>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c69758c650>: Failed to establish a new connection: [Errno -2] Name or service not known',))

+ status=1
```
?

I think it's more about an infrastructure problem than a problem of this test. Moving installation to the only place may decrease failures, but they are still possible.

**Comment by julya935** [comment]
> > When I ran behave tests on power they would fail. The problem was with installation of this package. Here's the example
> 
> @julya935, Are you about this fail:
> 
> ```
> Collecting allure-behave==2.4.0
>   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c6975cdb50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
>   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c6976f2750>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
> 1 feature passed, 0 failed, 22 skipped
> 10 scenarios passed, 0 failed, 424 skipped
> 93 steps passed, 0 failed, 5147 skipped, 0 undefined
> Took 12m33.163s
> 
> real	12m41.526s
> user	1m54.597s
> sys	0m42.935s
> + status=0
> + docker-compose -p gpmovemirrors_demo -f arenadata/docker-compose.yaml --env-file arenadata/.env down -v
>   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c69758c110>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
> Stopping gpmovemirrors_demo_sdw1_1 ... 
> Stopping gpmovemirrors_demo_sdw3_1 ... 
> Stopping gpmovemirrors_demo_mdw_1  ... 
> Stopping gpmovemirrors_demo_sdw2_1 ... 
>   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c69758c2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
>   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c69758c490>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl
> ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/32/c9/81c5293314053c66c5984af66b8d8258e627bcddd83e2dd69814feb1c96c/allure_behave-2.4.0-py2.py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x74c69758c650>: Failed to establish a new connection: [Errno -2] Name or service not known',))
> 
> + status=1
> ```
> 
> ?
> 
> I think it's more about an infrastructure problem than a problem of this test. Moving installation to the only place may decrease failures, but they are still possible.

@Stolb27 yeah, it might not be a test problem but we're not sure why this problem occurred. We'll keep it in mind and see if this problem pops up again. For now this is the only way of fixing the problem that we found

**Comment by Stolb27** [comment]
@julya935, can you explain why only x86_64 tests were run?

**Comment by julya935** [comment]
> @julya935, can you explain why only x86_64 tests were run?

@Stolb27 Sure. Yesterday there was sth with Power VM creation. Dynamic slaves failed with error while creation https://arenadataio.slack.com/archives/CAX5TP942/p1636347800159300 . The problem was fixed and I've restarted a build

**Review by Stolb27 — APPROVED** [review]

**Pull request merged**
