### PR TITLE
NOT FOR MERGE / Ci 3135 test

### PR DESCRIPTION
**Pull request by swork12**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Build ubuntu22 for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1846868

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1846867

**Comment by swork12** [comment]
bender build

**Comment by BenderArenadata** [comment]
Failed job Build ubuntu22 for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1874718

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1874717

**Comment by swork12** [comment]
Ticket closed

**Pull request closed without merging**
