### PR TITLE
Update README.md and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by andr-sokolov**
Move CONTRIBUTING.md from .github to the root. Replace the contents of
CONTRIBUTING.md in README.md with a link to avoid the text duplication.
Actualize the contents of CONTRIBUTING.md and README.md: update branch names and
links, remove mentions of the mailing list, etc.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/72964

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1510895

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1570015

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/73973

**Review by InnerLife0 — DISMISSED** [review]

**Review by InnerLife0 — APPROVED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/74349

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1598025

**Pull request merged**
