### PR TITLE
ADBDEV-6592: Treat S3 errors as query errors (#1097)

### PR DESCRIPTION
**Pull request by silent-observer**
Treat S3 errors as query errors

It is possible for reader_cleanup and writer_cleanup to produce errors (via S3Exception), resulting in incorrect query completion. Errors in these functions should be treated as ERRORs, not WARNINGs.

However, we cannot throw ERRORs inside resource owner callbacks, so during an actual abort we still use WARNINGs. This shouldn't be an issue because such an abort should only occur in erroneous conditions anyway.

Tests are not presented, as there is no existing test infrastructure to make an auto test with S3 storage.

Ticket: ADBDEV-6588
(cherry picked from commit 31895ff2311706c93a0e1335e7ebb07c47789dd4)

---

Note: Do not squash to preserve authorship

### CODE REVIEW

**Review by bimboterminator1 — APPROVED** [review]
LGTM.

**Comment by hilltracer** [comment]
Please write a scenario explaining how I can reproduce the problem and get these warnings: Failed to cleanup gpcloud extension... during export, import, and AbortCallback.

**Comment by silent-observer** [comment]
To reproduce: revert [this](https://github.com/arenadata/gpdb/pull/1095) patch to make the error reproducible and perform steps from [this](https://tracker.yandex.ru/ADBDEV-6543) ticket. This should reproduce the export error. Import error is equivalent but with select instead of insert. Error in AbortCallback is harder to reproduce, you would have to pause the export before it enters `destroyGpcloudResHandle` (with a debugger or a new fault injector), and then abort the process (by causing a panic in a different session, for example)

**Comment by hilltracer** [comment]
> To reproduce: revert [this](https://github.com/arenadata/gpdb/pull/1095) patch to make the error reproducible and perform steps from [this](https://tracker.yandex.ru/ADBDEV-6543) ticket. This should reproduce the export error. Import error is equivalent but with select instead of insert. Error in AbortCallback is harder to reproduce, you would have to pause the export before it enters `destroyGpcloudResHandle` (with a debugger or a new fault injector), and then abort the process (by causing a panic in a different session, for example)

After revert [this](https://github.com/arenadata/gpdb/pull/1095) patch. I still can't reproduce import scenario. @silent-observer  could you please provide scenario for import error branch testing? I think we have to test this branch.
```sql
postgres=# DROP FOREIGN TABLE public.ext_s3_write_test;

CREATE WRITABLE EXTERNAL TABLE public.ext_s3_write_test (
    a int,
    b float,
    c text
)
LOCATION (
    's3://localhost:9000/retest-1/write_test.csv region=ru-central1 config=/home/den/s3/s3cfg.conf'
)
FORMAT 'CSV';
DROP FOREIGN TABLE
CREATE EXTERNAL TABLE
postgres=# INSERT INTO public.ext_s3_write_test
SELECT i, 1.11, 'one'
FROM generate_series(10, 20) AS i;
ERROR:  Failed to cleanup gpcloud extension: writer_cleanup caught a S3LogicError exception: AWS returns error InvalidRequest : You must specify at least one part, Function: completeMultiPart, File: src/s3interface.cpp(557). (gpcloud.cpp:229)  (seg0 127.0.1.1:7002 pid=195494) (gpcloud.cpp:229)
postgres=# SELECT * FROM public.ext_s3_write_test;
ERROR:  cannot read from a WRITABLE external table
HINT:  Create the table as READABLE instead.
postgres=# DROP FOREIGN TABLE public.ext_s3_read_test;

CREATE READABLE EXTERNAL TABLE public.ext_s3_read_test (
    a int,
    b float,
    c text
)
LOCATION (
    's3://localhost:9000/retest-1/write_test.csv region=ru-central1 config=/home/den/s3/s3cfg.conf'
)
FORMAT 'CSV';
DROP FOREIGN TABLE
CREATE EXTERNAL TABLE
postgres=# SELECT * FROM public.ext_s3_read_test;
 a  |  b   |  c  
----+------+-----
 10 | 1.11 | one
 11 | 1.11 | one
 16 | 1.11 | one
 18 | 1.11 | one
 20 | 1.11 | one
 ...
```

**Comment by silent-observer** [comment]
Right, that patch only affects export, not import. For import there is no known reliable way to produce an error during the cleanup, but you can simulate that by adding something like `throw new S3LogicError("Code", "Text");` into `reader_cleanup()` function which should simulate that code path.

**Review by hilltracer — APPROVED** [review]

**Pull request merged**
