### PR TITLE
ADBDEV-5645 Add support ubuntu 22.04 to gpdb  6 sources

### PR DESCRIPTION
**Pull request by deart2k**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1427404

**Comment by BenderArenadata** [comment]
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1427460

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1427461

**Comment by Stolb27** [comment]
Waiting for #954 to fix pipelines

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/71463

**Comment by BenderArenadata** [comment]
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1454357

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/71859

**Comment by Stolb27** [comment]
@deart2k, there are more changes for other distros (e.g. [here](https://github.com/arenadata/gpdb/commit/936397cf3aabd8827331094f940d63db2e5bc535)). Is it correct?

**Comment by deart2k** [comment]
> @deart2k, there are more changes for other distros (e.g. [here](https://github.com/arenadata/gpdb/commit/936397cf3aabd8827331094f940d63db2e5bc535)). Is it correct?

As I understand it, other changes are not needed, since they affect the features of those operating systems

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/72198

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/72206

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/72210

**Review by Stolb27 — APPROVED** [review]

**Pull request merged**
