### PR TITLE
Make "lc_time" and "lc_monetary" sync GUCs

### PR DESCRIPTION
**Pull request by whitehawk**
Make "lc_time" and "lc_monetary" sync GUCs

Problem:
'lc_time' parameter was reset to default value on the segments after some time 
during the same session.

Cause:
The problem was caused by 'lc_time' guc definition that did’t contain 
requirements for sync. After 'gp_vmem_idle_resource_timeout' elapsed, new gangs 
on the segment DBs were initialized with the default (from config file) GUC 
value.

The problem is fixed by backport of e1a4fdb03edd091b9adc8504c3ed46385241b41c

In the test, the query with the call to 'pg_terminate_backend' has been wrapped
in 'ignore' section. Reason is that on 6x this query is planned in such a way
that the function is called on the segments with arguments (PIDs) collected from
all the cluster. That resulted in several warnings "WARNING: PID XXXXXX is not a
PostgreSQL server process" (and each time the count can be different), before it
actually terminated the backend process.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68427

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1245202

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1245203

**Comment by RekGRpth** [comment]
backport should be cherry-pick to save authorship
also you need explicit point, what was changed and why

**Comment by whitehawk** [comment]
> backport should be cherry-pick to save authorship
also you need explicit point, what was changed and why

fixed

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68497

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1250488

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1250490

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1250496

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1250497

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1251125

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1251126

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1252674

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1252675

**Comment by whitehawk** [comment]
bender build

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68541

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1252713

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1252714

**Review by RekGRpth — APPROVED** [review]

**Comment by bandetto** [comment]
Since this PR will get squashed and merged, due to us using PR description as the commit message, you need to add the authors of cherry-picked commit somewhere to the bottom of the PR description. You can copy-paste this:
```
Co-authored-by: dreamedcheng \<drec.wu@gmail.com\>
Co-authored-by: wuchengwen \<wcw190496@alibaba-inc.com\>
```
(backslashes are required, otherwise Github removes '<' and '>')

**Comment by RekGRpth** [comment]
> Since this PR will get squashed and merged, due to us using PR description as the commit message

I think this PR should be merged as one commit only and commit message should be taken from this commit not PR description

**Comment by bandetto** [comment]
> I think this PR should be merged as one commit only

If this PR would get rebased, then this is OK.

**Review by bandetto — APPROVED** [review]

**Comment by RekGRpth** [comment]
> > I think this PR should be merged as one commit only
> 
> If this PR would get rebased, then this is OK.

I think we always do so for backports, because they may contain several different commits from different authors

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/68792

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1270875

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1270876

**Pull request merged**
