### PR TITLE
Fix static analyzer warnings

### PR DESCRIPTION
**Pull request by andr-sokolov**

### CODE REVIEW

**Comment by andr-sokolov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/64309

**Comment by BenderArenadata** [comment]
Allure report https://allure-ee.adsw.io/launch/64310

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1062956

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1063312

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1062957

**Comment by BenderArenadata** [comment]
Failed job Regression tests with ORCA on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1062950

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1063313

**Review by RekGRpth — APPROVED** [review]

**Pull request merged**
