### PR TITLE
Update installation instructions on Ubuntu 20.04 or 22.04

### PR DESCRIPTION
**Pull request by hilltracer**
Add support for Ubuntu version 20.04 or 22.04. List of changes:

- Update installing dependencies.
- Create a symbolic link to Python 2.
- Update some common platform steps.

The correctness check was performed on a clean versions 20.04 and 22.04 of Ubuntu.

### CODE REVIEW

**Review by dkovalev1 — COMMENTED** [review]
Everything looks good, but README.md is missing. It has important change with replacing inaccessible repository.

**Review by dkovalev1 — APPROVED** [review]
README.md has corrected in target branch already. Looks good.

**Review by red1452 — APPROVED** [review]

**Comment by andr-sokolov** [comment]
bender build

**Comment by andr-sokolov** [comment]
bender build

**Comment by andr-sokolov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/74470

**Pull request merged**
