### PR TITLE
ORCA: Enable LOJ->IJ transformation with strict function call predicates

### PR DESCRIPTION
**Pull request by maksm90**
## Problem description
Currently ORCA considers non-volatile scalar functions that contain SQL (the value of attribute `prodataaccess` of pg_proc entry haven't to be equal to 'n') as not null-rejecting and hence doesn't performs transformation from LOJ to inner-join when outer predicate contains such functions over inner relation's attributes as conjuncts despite of whether these functions are strict by definition, e.g.:

```sql
explain (costs off)
select * from t1 left join t2 using (i)
where extract (hour from t2.t) = 5;

 Gather Motion 1:1  (slice1; segments: 1)
   ->  Result
         Filter: (date_part('hour'::text, t2.t) = 5::double precision)
         ->  Hash Left Join
               Hash Cond: (t1.i = t2.i)
               ->  Seq Scan on t1
               ->  Hash
                     ->  Seq Scan on t2
 Optimizer: Pivotal Optimizer (GPORCA)
```
The `date_part` function in the example above is strict and predicate under `Result` node is in fact null-rejecting for attribute `t` from inner relation `t2`. This kind of predicates allow LOJ transformation to Inner Join with successive predicate pushing down.

The current patch eliminates this restriction removing all guard conditions for LOJ->IJ transformation regarding characteristics of
scalar functions delegating the checks on function strictness to `EberEvaluate` routine that for scalar functions [indirectly uses](https://github.com/greenplum-db/gpdb/blob/6.13.0/src/backend/gporca/libgpopt/src/operators/CScalarFunc.cpp#L248-L251) their strictness property from `pg_proc`.

### CODE REVIEW

**Review by Stolb27 — COMMENTED** [review]
@maksm90 can you explain why we remove check for any other volatile functions?

Also, there are other places where we make a decision based on the value of `prodataaccess` attribute in GPORCA code:

```
GetFuncDataAccess()
  m_efda
    Efda()
      PcrsUsedByPushableScalar
      FNullRejecting
  PexprLogicalTVF
    m_has_volatile_or_SQL_func
      HasVolatileOrSQLFunc()
        OptimizeDMLQueryWithSingletonSegment
          CDistributionSpecSingleton()
          PdsRequiredSingleton()
```

But I didn't find places in gpdb which use this attribute. So it seems it is only ORCA case.

**Comment by darthunix** [comment]
@maksm90 as far as I understood, `scalar` expression, applied to some value, returns exactly one row containing a single column or NULL. Am I right? And for some reasons ORCA additionally requires scalar expressions not to be  marked volatile or not be written on SQL.

I have no idea why do we need these requirements - I didn't find any transformation rules, depending on this conditions. The only strange place in GPDB code, where `scalar expressions` were mentioned, was [CachedExpression](https://github.com/greenplum-db/gpdb/blob/e6379821da0f79ddf1cd95fc7ea34c9aa4c1e1c0/src/include/utils/plancache.h#L162) comment - some SQL functions can be inlined into expressions and cached, but it doesn't seems to be interconnected with ORCA limitations (it requires scalar expressions to be non-SQL). So, strictly saying, the problem is that we don't have a correct definition of `scalar expression` for ORCA.

But the main question is - what problem do we solve? AFAICS, the original problem was solved with https://github.com/arenadata/gpdb/pull/153 as `date_part`'s value of attribute `prodataaccess` of `pg_proc` was incorrect. Do we actually need this PR? May be we should not fix a complicated system when it is not broken?

**Comment by maksm90** [comment]
@darthunix 

> `scalar` expression, applied to some value, returns exactly one row containing a single column or NULL. Am I right?

IMO this row might have multiple columns, not necessarily one.

> And for some reasons ORCA additionally requires scalar expressions not to be marked volatile or not be written on SQL.

Yes, it haven't to contain volatile functions and functions with SQL body.

> I have no idea why do we need these requirements - I didn't find any transformation rules, depending on this conditions. The only strange place in GPDB code, where `scalar expressions` were mentioned, was [CachedExpression](https://github.com/greenplum-db/gpdb/blob/e6379821da0f79ddf1cd95fc7ea34c9aa4c1e1c0/src/include/utils/plancache.h#L162) comment - some SQL functions can be inlined into expressions and cached, but it doesn't seems to be interconnected with ORCA limitations (it requires scalar expressions to be non-SQL). So, strictly saying, the problem is that we don't have a correct definition of `scalar expression` for ORCA.

I don't fully understand your point above. The scalar expression is clearly ORCA abstraction that is defined as specific base class `CScalar` that is kind of `COperator` along side logical, physical operators and patterns. All children of `CScalar` class are the real representations of scalar expression, e.g., scalar function (`CScalarFunction` class), bitmap bool operation (`CScalarBitmapBoolOp` class), scalar constant (`CScalarConst` class), etc.

> But the main question is - what problem do we solve? AFAICS, the original problem was solved with #153 as `date_part`'s value of attribute `prodataaccess` of `pg_proc` was incorrect. 

Yes, after fix in #153 the customer's issue might be viewed as solved

> Do we actually need this PR?

The patch addresses to more rigorous cases of using function calls in predicate, e.g., when

- function is volatile (or defined as volatile due to the negligence of author) but strict
- function is defined as plpgsql and cannot be inlined to upper query and further pass check on LOJ->IJ transformation
- etc.

> May be we should not fix a complicated system when it is not broken?

It makes sense but I would like to make fundamental improvement in allowability of LOJ->IJ transformation

**Comment by maksm90** [comment]
@Stolb27 

> @maksm90 can you explain why we remove check for any other volatile functions?

I think the strictness property of scalar function is enough for definition of null-rejecting criteria for predicate in which any kind (volatile or not) function call is contained. The strictness property is unambiguous about returning null value that filters incoming rows under receiving of some null argument values and this is [checked](https://github.com/greenplum-db/gpdb/blob/6.13.0/src/backend/gporca/libgpopt/src/operators/CScalarFunc.cpp#L248-L253) at the time of predicate expression evaluation for scalar function call:
```C++
CScalar::EBoolEvalResult
CScalarFunc::Eber(ULongPtrArray *pdrgpulChildren) const
{
	if (m_returns_null_on_null_input)
	{
		return EberNullOnAnyNullChild(pdrgpulChildren);
	}

	return EberAny;
}
```
 Postgres optimizer as well fluently performs LOJ->IJ transformation and pushes predicate down when this predicate is represented as volatile function or some expression around it:
```sql
CREATE OR REPLACE FUNCTION public.test(t timestamp without time zone)
 RETURNS boolean
 LANGUAGE sql
 STRICT VOLATILE
AS $function$
select 1;
select t > now() - interval '5 minutes';
$function$;

set optimizer to off;
explain select * from t1 left join t2 using(i) where test(t2.t);
                                        QUERY PLAN                                         
-------------------------------------------------------------------------------------------
 Gather Motion 1:1  (slice1; segments: 1)  (cost=2266.75..360265.28 rows=2500590 width=12)
   ->  Hash Join  (cost=2266.75..360265.28 rows=2500590 width=12)
         Hash Cond: (t2.i = t1.i)
         ->  Seq Scan on t2  (cost=0.00..20354.00 rows=25967 width=12)
               Filter: test(t)
         ->  Hash  (cost=1063.00..1063.00 rows=96300 width=4)
               ->  Seq Scan on t1  (cost=0.00..1063.00 rows=96300 width=4)
 Optimizer: Postgres query optimizer
```

**Comment by darthunix** [comment]
@maksm90 I would try to clarify my questions.
1. What the definition of `scalar expressions` in ORCA? Do they have some optimisations during planning flow that can cause  non-volatile and non-SQL function requirements? May be it is more safe to add a special bypass for strict functions in scalar expressions rather than remove current restrictions?
2. Can you replace your test minidump with the one with custom functions representing the problem? Because current example is caused by https://github.com/arenadata/gpdb/pull/153 and doesn't explain the problem solved by this PR. AFAICS from the code, `FNullRejecting()` is used only in a few join transformations where we check a NULL-filtering predicate (LOJ -> IJ, FJ -> LOJ). It would be nice to show these examples in test minidumps.

**Comment by maksm90** [comment]
@Stolb27 @darthunix your concerns about volatile functions inside predicate make sense. For example, predicate pushdown under inner join in the following example forces query to return incorrect number of rows (PostgreSQL 14devel case):
```sql
# function predicate that filters copies of timestamp argument
CREATE OR REPLACE FUNCTION public.eliminate_copies_predicate(t timestamp without time zone)
 RETURNS boolean
 LANGUAGE plpgsql
 STRICT
AS $function$
begin
    create temp table if not exists ts_set (
        t timestamp unique
    ) on commit drop;

    insert into ts_set
    values (t)
    on conflict do nothing;

    return found;
end;
$function$;

# inner relation contains same values in filtering attribute
create table t2 as select i, now()::timestamp without time zone as t from generate_series(1, 10) i;

# outer relation contains same values in join key to produce copies of tuples from inner relation 
create table t1 as select 1 from generate_series(1, 10) i;

# predicate `eliminate_copies_predicate()` is pushed down under inner join
# as a result, joint tuples with the same timestamp attribute are not filtered that would be otherwise when predicate is applied above join
explain (costs off, analyze)
select * from t1 join t2 using(i)
where eliminate_copies_predicate(t2.t);
                               QUERY PLAN                               
------------------------------------------------------------------------
 Hash Join (actual time=19.746..19.778 rows=10 loops=1)
   Hash Cond: (t1.i = t2.i)
   ->  Seq Scan on t1 (actual time=0.424..0.431 rows=10 loops=1)
   ->  Hash (actual time=19.264..19.266 rows=1 loops=1)
         Buckets: 1024  Batches: 1  Memory Usage: 9kB
         ->  Seq Scan on t2 (actual time=17.297..19.250 rows=1 loops=1)
               Filter: eliminate_copies_predicate(t)
               Rows Removed by Filter: 9
```
GPDB inhibits to execute writable function in predicate inside read-only gang.

In sum, volatile functions have not to be pushed down under the join but the sole LOJ->IJ transformation could be performed and therefore the fix inside `FNullRejecting()` have to be left in place.

**Comment by darthunix** [comment]
@maksm90 do you plan to open a discussion in postgres hackers about volatile functions and predicate pushdown? It seems incorrect that these queries return different answers on 14devel:
```sql
-- single tuple (no push down, filter tuples after join)
with t(i, t) as materialized (select * from t1 join t2 using(i))
select * from t where eliminate_copies_predicate(t);

-- 10 tuples (push down volatile function under join)
with t(i, t) as not materialized (select * from t1 join t2 using(i))
select * from t where eliminate_copies_predicate(t);
```

**Comment by maksm90** [comment]
> @maksm90 do you plan to open a discussion in postgres hackers about volatile functions and predicate pushdown? It seems incorrect that these queries return different answers on 14devel

Yes, later

**Comment by Stolb27** [comment]
HasSQL part was removed years ago by the upstream 894d868ae8c483ce78d8424a3f5a8251b572b414. Correctness of volatile functions push down needs deeper research. I've reworded the original ticket. Close this one for now.

**Pull request closed without merging**
