### PR TITLE
ADBDEV-6909-6X: Remove greenplum-specific documentation

### PR DESCRIPTION
**Pull request by RekGRpth**
Remove greenplum-specific documentation

The greenplum-specific documentation will be implemented in a new separate
project.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/89315

**Review by andr-sokolov — DISMISSED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/89378

**Comment by andr-sokolov** [comment]
Can we remove these references?
```
gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb6_pr.yml:40:        - gpdb-doc/*
gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb7_release.yml:24:        - gpdb-doc/*
gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb6_and_gpdb7_pr.yml:40:        - gpdb-doc/*
gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb6_and_gpdb7_pr.yml:87:        - gpdb-doc/*
gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb5_pr.yml:39:    - gpdb-doc/*
```

**Comment by RekGRpth** [comment]
> Can we remove these references?
> 
> ```
> gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb6_pr.yml:40:        - gpdb-doc/*
> gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb7_release.yml:24:        - gpdb-doc/*
> gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb6_and_gpdb7_pr.yml:40:        - gpdb-doc/*
> gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb6_and_gpdb7_pr.yml:87:        - gpdb-doc/*
> gpAux/extensions/pgbouncer/source/concourse/pipelines/bouncer_gpdb5_pr.yml:39:    - gpdb-doc/*
> ```

Yes, but that's a [different](https://github.com/arenadata/gpdb/blob/cbb3338b7472ea34ddb25ddf1aebf83d6d82388c/.gitmodules#L3) project.

**Review by andr-sokolov — APPROVED** [review]

**Pull request merged**
