### PR TITLE
Test

### PR DESCRIPTION
**Pull request by swork12**

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Deploy multiarch Dockerimages: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1874950

**Comment by BenderArenadata** [comment]
Failed job Deploy multiarch Dockerimages: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1875159

**Comment by BenderArenadata** [comment]
Failed job Deploy multiarch Dockerimages: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1875161

**Comment by swork12** [comment]
bender build

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/79631

**Comment by swork12** [comment]
bender build

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/79638

**Comment by swork12** [comment]
bender build

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/79668

**Comment by swork12** [comment]
Test done

**Pull request closed without merging**
