### PR TITLE
ADBDEV-3098: ORCA produces bogus plan for queries with CTE during handling distribution for Sequence children

### PR DESCRIPTION
**Pull request by RekGRpth**
With some conditions ORCA generates `Redistribute Motion` from all segments to one segment or plan which can not executed because inconsistency CTE producers and consumers.
For example, run query with one CTE
```sql
CREATE TABLE d (a int, b int, c int) DISTRIBUTED BY (a);
CREATE TABLE r (a int, b int, c char(255)) DISTRIBUTED REPLICATED;
INSERT INTO d SELECT 1, generate_series(1,10), 1;
INSERT INTO r SELECT 1, 2, generate_series(1,100);
EXPLAIN (ANALYZE off, COSTS off, VERBOSE off)
WITH e AS (
    SELECT DISTINCT b FROM d
) SELECT * FROM r JOIN e USING (b) JOIN e f USING (b);
```
That gives bogus plan
```sql
 Gather Motion 1:1  (slice3; segments: 1)
   ->  Sequence
         ->  Shared Scan (share slice:id 3:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d.b
                           ->  Sort
                                 Sort Key: d.b
                                 ->  Redistribute Motion 3:1  (slice2; segments: 3)
                                       Hash Key: d.b
                                       ->  Seq Scan on d
         ->  Hash Join
               Hash Cond: (r.b = share0_ref3.b)
               ->  Seq Scan on r
               ->  Hash
                     ->  Broadcast Motion 3:1  (slice1; segments: 3)
                           ->  Hash Join
                                 Hash Cond: (share0_ref3.b = share0_ref2.b)
                                 ->  Shared Scan (share slice:id 1:0)
                                 ->  Hash
                                       ->  Shared Scan (share slice:id 1:0)
 Optimizer: Pivotal Optimizer (GPORCA)
(22 rows)
```
In this plan `Shared Scan (share slice:id 3:0)` is CTE producer that is executed only on one segment because `Redistribute Motion 3:1  (slice2; segments: 3)`, but both CTE consumers (`Shared Scan (share slice:id 1:0)`) are executed on all 3 segments and then query hangs.
Or run query with two CTEs one of which is inlined by filter
```sql
CREATE TABLE d (a int, b int, c int) DISTRIBUTED BY (a);
CREATE TABLE r (a int, b int, c char(255)) DISTRIBUTED REPLICATED;
INSERT INTO d SELECT 1, generate_series(1,10), 1;
INSERT INTO r SELECT 1, 2, generate_series(1,100);
EXPLAIN (ANALYZE off, COSTS off, VERBOSE off)
WITH e AS (
    SELECT DISTINCT b FROM d
), h AS (
    SELECT a FROM d JOIN e f USING (b) JOIN e USING (b)
) SELECT * FROM r JOIN h USING (a);
```
That gives bogus plan
```sql
 Gather Motion 1:1  (slice4; segments: 1)
   ->  Sequence
         ->  Shared Scan (share slice:id 4:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d_1.b
                           ->  Sort
                                 Sort Key: d_1.b
                                 ->  Redistribute Motion 3:1  (slice3; segments: 3)
                                       Hash Key: d_1.b
                                       ->  Seq Scan on d d_1
         ->  Hash Join
               Hash Cond: (r.a = d.a)
               ->  Seq Scan on r
               ->  Hash
                     ->  Broadcast Motion 3:1  (slice2; segments: 3)
                           ->  Hash Join
                                 Hash Cond: (d.b = share0_ref3.b)
                                 ->  Redistribute Motion 3:3  (slice1; segments: 3)
                                       Hash Key: d.b
                                       ->  Seq Scan on d
                                 ->  Hash
                                       ->  Hash Join
                                             Hash Cond: (share0_ref3.b = share0_ref2.b)
                                             ->  Shared Scan (share slice:id 2:0)
                                             ->  Hash
                                                   ->  Shared Scan (share slice:id 2:0)
 Optimizer: Pivotal Optimizer (GPORCA)
(28 rows)
```
In this plan `Shared Scan (share slice:id 4:0)` is CTE producer that is executed only on one segment because `Redistribute Motion 3:1  (slice3; segments: 3)`, but both CTE consumers (`Shared Scan (share slice:id 2:0)`) are executed on all 3 segments and then query hangs.
Or run query with two CTEs
```sql
CREATE TABLE d (a int, b int, c int) DISTRIBUTED BY (a);
CREATE TABLE r (a int, b int, c char(255)) DISTRIBUTED REPLICATED;
--INSERT INTO d SELECT 1, generate_series(1,10), 1; -- table d must be empty!
--INSERT INTO r SELECT 1, 2, generate_series(1,100); -- table r must be empty!
EXPLAIN (ANALYZE off, COSTS off, VERBOSE off)
WITH e AS (
    SELECT DISTINCT b FROM d
), h AS (
    SELECT a FROM d JOIN e f USING (b) JOIN e USING (b)
) SELECT * FROM r JOIN h USING (a) JOIN h i USING (a);
```
That gives bogus plan
```sql
 Gather Motion 1:1  (slice5; segments: 1)
   ->  Sequence
         ->  Shared Scan (share slice:id 5:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d_1.b
                           ->  Sort
                                 Sort Key: d_1.b
                                 ->  Redistribute Motion 3:1  (slice4; segments: 3)
                                       Hash Key: d_1.b
                                       ->  Seq Scan on d d_1
         ->  Sequence
               ->  Shared Scan (share slice:id 5:1)
                     ->  Materialize
                           ->  Hash Join
                                 Hash Cond: (d.b = share0_ref2.b)
                                 ->  Hash Join
                                       Hash Cond: (d.b = share0_ref3.b)
                                       ->  Redistribute Motion 3:1  (slice3; segments: 3)
                                             Hash Key: d.b
                                             ->  Seq Scan on d
                                       ->  Hash
                                             ->  Shared Scan (share slice:id 5:0)
                                 ->  Hash
                                       ->  Shared Scan (share slice:id 5:0)
               ->  Hash Join
                     Hash Cond: ((r.a = share1_ref3.a) AND (r.a = share1_ref2.a))
                     ->  Seq Scan on r
                     ->  Hash
                           ->  Broadcast Motion 3:1  (slice2; segments: 3)
                                 ->  Hash Join
                                       Hash Cond: (share1_ref3.a = share1_ref2.a)
                                       ->  Shared Scan (share slice:id 2:1)
                                       ->  Hash
                                             ->  Broadcast Motion 3:3  (slice1; segments: 3)
                                                   ->  Shared Scan (share slice:id 1:1)
 Optimizer: Pivotal Optimizer (GPORCA)
(37 rows)
```
In this plan `Shared Scan (share slice:id 5:0)` and `Shared Scan (share slice:id 5:1)` are CTE producers which are executed only on one segment because `Redistribute Motion 3:1  (slice3; segments: 3)` and `Redistribute Motion 3:1  (slice4; segments: 3)`, but CTE consumers (`Shared Scan (share slice:id 5:0)` and `Shared Scan (share slice:id 2:1)` and `Shared Scan (share slice:id 1:1)`) are executed on all 3 segments and then query hangs.
We get Redistribute N:1 because following. When translating expression to DXL, ORCA sets one segment for input array if strict or tainted replicated https://github.com/arenadata/gpdb/blob/2104e0653b8a98ab42ce3fbd2324cc1b750a491b/src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp#L8236-L8264 and this one segment is used as output array for below motions including redistribute and broadcast.
Solution is prohibit replicated distribution when required distribution in sequence is singleton on master or non-singleton with prohibited replicated.
In case of inlining one CTE we also need push down non-singleton with prohibited replicated through filter. ( Filter is appeared when CTE may be inlined and inlining allowed or only one consumer exists for that CTE
https://github.com/arenadata/gpdb/blob/2104e0653b8a98ab42ce3fbd2324cc1b750a491b/src/backend/gporca/libgpopt/src/xforms/CXformCTEAnchor2TrivialSelect.cpp#L57-L61
in that case ORCA append logical select
https://github.com/arenadata/gpdb/blob/2104e0653b8a98ab42ce3fbd2324cc1b750a491b/src/backend/gporca/libgpopt/src/xforms/CXformCTEAnchor2TrivialSelect.cpp#L103-L105
which later is translated to filter
https://github.com/arenadata/gpdb/blob/2104e0653b8a98ab42ce3fbd2324cc1b750a491b/src/backend/gporca/libgpopt/src/xforms/CXformSelect2Filter.cpp#L94-L95 )
It is gives right plans.
For one CTE
```sql
 Gather Motion 3:1  (slice2; segments: 3)
   ->  Sequence
         ->  Shared Scan (share slice:id 2:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d.b
                           ->  Sort
                                 Sort Key: d.b
                                 ->  Redistribute Motion 3:3  (slice1; segments: 3)
                                       Hash Key: d.b
                                       ->  Seq Scan on d
         ->  Hash Join
               Hash Cond: (r.b = share0_ref3.b)
               ->  Result
                     ->  Seq Scan on r
               ->  Hash
                     ->  Hash Join
                           Hash Cond: (share0_ref3.b = share0_ref2.b)
                           ->  Shared Scan (share slice:id 2:0)
                           ->  Hash
                                 ->  Shared Scan (share slice:id 2:0)
 Optimizer: Pivotal Optimizer (GPORCA)
(22 rows)
```
For two CTEs one of which is inlined by filter
```sql
 Gather Motion 3:1  (slice4; segments: 3)
   ->  Sequence
         ->  Shared Scan (share slice:id 4:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d_1.b
                           ->  Sort
                                 Sort Key: d_1.b
                                 ->  Redistribute Motion 3:3  (slice3; segments: 3)
                                       Hash Key: d_1.b
                                       ->  Seq Scan on d d_1
         ->  Hash Join
               Hash Cond: (r.a = d.a)
               ->  Result
                     ->  Seq Scan on r
               ->  Hash
                     ->  Redistribute Motion 3:3  (slice2; segments: 3)
                           Hash Key: d.a
                           ->  Hash Join
                                 Hash Cond: (d.b = share0_ref3.b)
                                 ->  Redistribute Motion 3:3  (slice1; segments: 3)
                                       Hash Key: d.b
                                       ->  Seq Scan on d
                                 ->  Hash
                                       ->  Hash Join
                                             Hash Cond: (share0_ref3.b = share0_ref2.b)
                                             ->  Shared Scan (share slice:id 2:0)
                                             ->  Hash
                                                   ->  Shared Scan (share slice:id 2:0)
 Optimizer: Pivotal Optimizer (GPORCA)
(30 rows)
```
For two CTEs
```sql
 Gather Motion 3:1  (slice5; segments: 3)
   ->  Sequence
         ->  Shared Scan (share slice:id 5:0)
               ->  Materialize
                     ->  GroupAggregate
                           Group Key: d_1.b
                           ->  Sort
                                 Sort Key: d_1.b
                                 ->  Redistribute Motion 3:3  (slice4; segments: 3)
                                       Hash Key: d_1.b
                                       ->  Seq Scan on d d_1
         ->  Sequence
               ->  Shared Scan (share slice:id 5:1)
                     ->  Materialize
                           ->  Hash Join
                                 Hash Cond: (d.b = share0_ref2.b)
                                 ->  Hash Join
                                       Hash Cond: (d.b = share0_ref3.b)
                                       ->  Redistribute Motion 3:3  (slice3; segments: 3)
                                             Hash Key: d.b
                                             ->  Seq Scan on d
                                       ->  Hash
                                             ->  Shared Scan (share slice:id 5:0)
                                 ->  Hash
                                       ->  Shared Scan (share slice:id 5:0)
               ->  Hash Join
                     Hash Cond: ((r.a = share1_ref3.a) AND (r.a = share1_ref2.a))
                     ->  Result
                           ->  Seq Scan on r
                     ->  Hash
                           ->  Redistribute Motion 3:3  (slice2; segments: 3)
                                 Hash Key: share1_ref3.a, share1_ref2.a
                                 ->  Hash Join
                                       Hash Cond: (share1_ref3.a = share1_ref2.a)
                                       ->  Shared Scan (share slice:id 2:1)
                                       ->  Hash
                                             ->  Broadcast Motion 3:3  (slice1; segments: 3)
                                                   ->  Shared Scan (share slice:id 1:1)
 Optimizer: Pivotal Optimizer (GPORCA)
(39 rows)
```
Upstream master (gpdb 7) also is affected by this problem, but with other error
```sql
FATAL:  Unexpected internal error (assert.c:44)
DETAIL:  FailedAssertion("!(pMotion->numHashSegments < motion_recv)", File: "explain.c", Line: 2513)
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

### CODE REVIEW

**Review by Stolb27 — CHANGES_REQUESTED** [review]
1. Provide description for your minidumps as described in the [article ](https://wiki.adsw.io/books/adb/page/orca-development) in our wiki. Describe that this test does, how to reproduce this minidump, that plan do you exepct and why. Take a look at good examples. You've asked me about minidumps without description and added three more. Do you joke?
2. Leave only meaning part of plans in the PR description. Take in account that plans is not a good description for reviewers. The better place for full plans is mdp description.
3. I think that `src/backend/gporca/server/src/unittest/gpopt/minidump/CCTETest.cpp` is the better place for your tests, especially when with chosen minidump naming style. What do you think?
4. Squash useless fixup commits and provide valid commit message without huge parts of plans. There must be a good text description for proposed changes.

**Comment by Stolb27** [comment]
> Solution is prohibit replicated distribution when required distribution in sequence is singleton on master or non-singleton with prohibited replicated.

In all "good" plans, there are Motion above Sequence operator. This operator requests Any distribution. Why does the condition in Sequence operator work after enforcement?

> In case of inlining one CTE we also need push down non-singleton with prohibited replicated through filter. It is gives right plans.

You didn't describe why filter comes to play, why it's needed, and why filter modification didn't affect other queries. E.g. `CTE-4.mdp` doesn't contain replicated tables or inlined CTE's. Why this patch affects this query?

**Comment by RekGRpth** [comment]
> 1. how to reproduce this minidump

done

**Comment by RekGRpth** [comment]
> 1. that plan do you exepct

done

**Comment by RekGRpth** [comment]
> 3\. I think that `src/backend/gporca/server/src/unittest/gpopt/minidump/CCTETest.cpp` is the better place for your tests, especially when with chosen minidump naming style. What do you think?

done

**Comment by RekGRpth** [comment]
> 2\. Leave only meaning part of plans in the PR description

removed physical plans from PR description

**Comment by RekGRpth** [comment]
> In all "good" plans, there are Motion above Sequence operator. This operator requests Any distribution. Why does the condition in Sequence operator work after enforcement?

new condition in sequence does not affect on motion appearance above sequence

**Comment by RekGRpth** [comment]
> You didn't describe why filter comes to play

filter is appeared when CTE may be inlined and inlining allowed or only one consumer exists for that CTE
https://github.com/arenadata/gpdb/blob/2104e0653b8a98ab42ce3fbd2324cc1b750a491b/src/backend/gporca/libgpopt/src/xforms/CXformCTEAnchor2TrivialSelect.cpp#L57-L61
in that case ORCA append logical select
https://github.com/arenadata/gpdb/blob/2104e0653b8a98ab42ce3fbd2324cc1b750a491b/src/backend/gporca/libgpopt/src/xforms/CXformCTEAnchor2TrivialSelect.cpp#L103-L105
which later is translated to filter
https://github.com/arenadata/gpdb/blob/2104e0653b8a98ab42ce3fbd2324cc1b750a491b/src/backend/gporca/libgpopt/src/xforms/CXformSelect2Filter.cpp#L94-L95

**Comment by RekGRpth** [comment]
> E.g. `CTE-4.mdp` doesn't contain replicated tables or inlined CTE's

I could reproduce this test via
```sql
CREATE TABLE foo (a int, b int) DISTRIBUTED BY (a);
EXPLAIN (ANALYZE off, COSTS off, VERBOSE off)
WITH cte1 AS (
    SELECT * FROM foo
), cte2 AS (
    SELECT * FROM cte1
) SELECT * FROM cte1 JOIN cte2 ON cte1.a = cte2.b;
```
that gives without patch
```sql
Physical plan: 
+--CPhysicalMotionGather(master)   rows:1   width:46  rebinds:1   cost:1293.000594   origin: [Grp:7, GrpExpr:3]
   +--CPhysicalSequence   rows:1   width:46  rebinds:1   cost:1293.000535   origin: [Grp:7, GrpExpr:2]
      |--CPhysicalCTEProducer (0), Columns: ["a" (0), "b" (1)]   rows:1   width:38  rebinds:1   cost:431.000012   origin: [Grp:10, GrpExpr:1]
      |  +--CPhysicalTableScan "foo" ("foo")   rows:1   width:38  rebinds:1   cost:431.000007   origin: [Grp:9, GrpExpr:1]
      +--CPhysicalFilter   rows:1   width:46  rebinds:1   cost:862.000517   origin: [Grp:6, GrpExpr:2]
         |--CPhysicalInnerHashJoin   rows:1   width:46  rebinds:1   cost:862.000517   origin: [Grp:5, GrpExpr:4]
         |  |--CPhysicalCTEConsumer (0), Columns: ["a" (18), "b" (19)]   rows:1   width:38  rebinds:1   cost:431.000019   origin: [Grp:0, GrpExpr:1]
         |  |--CPhysicalMotionHashDistribute HASHED: [ CScalarIdent "b" (28), nulls colocated ], opfamilies: (1977,1.0),   rows:1   width:8  rebinds:1   cost:431.000019   origin: [Grp:1, GrpExpr:6]
         |  |  +--CPhysicalCTEConsumer (0), Columns: ["a" (27), "b" (28)]   rows:1   width:8  rebinds:1   cost:431.000006   origin: [Grp:1, GrpExpr:2]
         |  +--CScalarCmp (=)   origin: [Grp:4, GrpExpr:0]
         |     |--CScalarIdent "a" (18)   origin: [Grp:2, GrpExpr:0]
         |     +--CScalarIdent "b" (28)   origin: [Grp:3, GrpExpr:0]
         +--CScalarConst (1)   origin: [Grp:8, GrpExpr:0]
                               QUERY PLAN                               
------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)
   ->  Sequence
         ->  Shared Scan (share slice:id 2:0)
               ->  Materialize
                     ->  Seq Scan on foo
         ->  Hash Join
               Hash Cond: (share0_ref3.a = share0_ref2.b)
               ->  Shared Scan (share slice:id 2:0)
               ->  Hash
                     ->  Redistribute Motion 3:3  (slice1; segments: 3)
                           Hash Key: share0_ref2.b
                           ->  Shared Scan (share slice:id 1:0)
 Optimizer: Pivotal Optimizer (GPORCA)
(13 rows)
```
it shows, that `CTE-4.mdp` contains inlined CTE, and replicated tables does not matter on `CPhysicalSequence::PdsRequired`, but we check replicated distribution later, that occurs always in join (it always generate replicated request)

**Comment by InnerLife0** [comment]
I've missed all the progress done over ADBDEV-3098 and can't say why exactly this iteration is the best, but for me generally all is OK, except:
- I still don't understand explanation of why `CTE-4.mdp` changed.
- I want to see the final commit message and review it. Obviously we need this and it should be more concise than PR description.

**Comment by RekGRpth** [comment]
> why `CTE-4.mdp` changed.

it is changed because we disable bad alternatives (which are not selecting due to cost reason)

**Comment by RekGRpth** [comment]
> * I want to see the final commit message and review it. Obviously we need this and it should be more concise than PR description.

With some conditions ORCA generates Redistribute Motion from all segments
to one segment or plan which can not executed because inconsistency
CTE producers and consumers.

In such plans Shared Scan is CTE producer that is executed only on one segment
(due to Redistribute Motion from all segments to one segments), but CTE
consumers are executed on all segments and then query hangs.

We get Redistribute from all segments to one segments because following. When
translating expression to DXL, ORCA sets one segment for input array if strict
or tainted replicated distribution and this one segment is used as output array
for below motions including redistribute and broadcast.

Solution is prohibit replicated distribution when required distribution in
sequence is singleton on master or non-singleton with prohibited replicated.

In case of inlining one CTE we also need push down non-singleton with
prohibited replicated through filter. Because filter is appeared when
CTE may be inlined and inlining allowed or only one consumer exists for
that CTE. In this case ORCA append logical select, which later is translated
to filter.

**Comment by InnerLife0** [comment]
> 
> With some conditions ...

I added minor fixes
_____________
With some conditions ORCA generates Redistribute Motion from all segments to one
segment or generates a plan which can't be executed by reason of inconsistency
between CTE producers and consumers.

In such plans Shared Scan is CTE producer that's executed only on one segment
(due to Redistribute Motion from all segments to one segments), but CTE
consumers are executed on all segments and then query hangs.

We get Redistribute from all segments to one segments because the following.
When translating expression to DXL, ORCA sets one segment for input array if
strict or tainted replicated distribution detected. This one segment is used as
output array for below motions including redistribute and broadcast.

Solution is to prohibit replicated distribution when required distribution in
sequence is singleton on master or non-singleton with prohibited replicated.

In case of inlining one CTE we also need to push down non-singleton with
prohibited replicated through filter. Because filter is appeared when CTE may be
inlined and inlining allowed or only one consumer exists for that CTE. In this
case ORCA append logical select, which later is translated to filter.

**Review by InnerLife0 — APPROVED** [review]

**Review by Stolb27 — APPROVED** [review]

**Pull request merged**
