### PR TITLE
ADBDEV-6155: Disable GUC gp_log_stack_trace_lines by default

### PR DESCRIPTION
**Pull request by KnightMurloc**
Disable GUC gp_log_stack_trace_lines by default

Gpdb uses addr2line to add file names and line numbers to the stack trace. But
addr2line can use a large amount of memory, the consumption of which we cannot
control, which can lead to OOM on the entire host. This behavior is controlled
by GUC gp_log_stack_trace_lines which is true by default.

This patch changes the default value for gp_log_stack_trace_lines to false so as
not to run addr2line every time the stack is logged.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/78187

**Review by whitehawk — APPROVED** [review]

**Review by bimboterminator1 — APPROVED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/78581

**Comment by BenderArenadata** [comment]
Failed job Regression tests with Postgres on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1823633

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/78596

**Pull request merged**
