### PR TITLE
ADBDEV-4792: Мake the gpexpand test more stable.

### PR DESCRIPTION
**Pull request by KnightMurloc**
Мake the gpexpand test more stable.
    
In some gpexpand tests, checks if the expand is interrupted after a set time,
but sometimes gpexpand may expand faster than the set time and the test will
fail.
    
This patch adds a 5-second sleep after the expansion of the first table to
stimulate a long expansion without increasing the amount of data. To add sleep,
a fault injector in the finish_heap_swap is used, which occurs during the
expansion of the table.

There was also a revert commit 41646c8d46ced65df8e1c712fc85716522f3c0d8 since we
no longer need such a volume of data for the test.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1107184

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1107740

**Comment by BenderArenadata** [comment]
Failed job Behave tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1107739

**Review by Stolb27 — COMMENTED** [review]
LGTM, but I have one question: maybe decrease amount of tuples inserted to tables as useless after applying your patch?  It'll help to compensate 5s sleep. Of course, by making greater the patch footprint as a trade-off. What's your opinion?

изображение

Also, I wanted to suggest replacing your new step with a [more common](https://github.com/arenadata/gpdb/blob/c6fbec66b249d001c828cbeb3f8bfe54d6d12a0f/gpMgmt/test/behave/mgmt_utils/gpstop.feature#L70-L71). But I think tour existing solution is closer to the spirit of BDD.

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1113013

**Comment by BenderArenadata** [comment]
Failed job Behave tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1113012

**Comment by RekGRpth** [comment]
The PR description does not mention reverting the commit.

**Comment by KnightMurloc** [comment]
I decided to return the old solution since it is more consistent with the style of behave tests.

**Comment by RekGRpth** [comment]
> I decided to return the old solution since it is more consistent with the style of behave tests.

but you revert one commit, while PR description does not mention reverting the commit
also, you may update branch for fixing gprecoverseg test

**Comment by KnightMurloc** [comment]
> but you revert one commit, while PR description does not mention reverting the commit

I have updated the description

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1115379

**Comment by BenderArenadata** [comment]
Failed job Behave tests 7: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1115378

**Review by RekGRpth — APPROVED** [review]

**Review by Stolb27 — APPROVED** [review]
@KnightMurloc, please merge it with rebase mode

**Pull request merged**
