### PR TITLE
ADBDEV-5103: Make frozen_insert_crash test stable

### PR DESCRIPTION
**Pull request by RekGRpth**
Make frozen_insert_crash test stable

Commit 1502bef introduced a new flaking test. The test expects a panic to occur
in the process that performs the insert. But sometimes the panic happens first
in process which started by dtx recovery process that periodically checks for
orphaned transactions. Which leads to an error in the test. The solution is to
panic only the required process, which is done by extracting session from
pg_stat_activity by query.

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/67041

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1183917

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1183918

**Comment by InnerLife0** [comment]
At the voice chat we discussed how to simplify the changes and reduce diff.
Second, I asked for a link to a process that checks for abandoned transactions.

**Comment by RekGRpth** [comment]
> simplify the changes and reduce diff

simplified

> a link to a process that checks for abandoned transactions

added

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/67247

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1194247

**Comment by InnerLife0** [comment]
Was able to reproduce a case by sleeping on src/backend/access/bitmap/bitmapattutil.c:341 in second session.
The stack is similar to target.
```
2024-03-22 17:57:44.259393 +05,"innerlife","postgres",p86688,th46145024,"127.0.0.1","33734",2024-03-22 17:57:44 +05,0,con1,,seg0,,,,,"PANIC","XX009","fault triggered, fault name:'qe_exec_finished' fault type:'panic'",,,,,,,0,,"faultinjector.c",378,"Stack trace:
1    0x55ef9b6fa1f6 postgres errstart + 0x442
2    0x55ef9b735960 postgres FaultInjector_InjectFaultIfSet_out_of_line + 0x5cc
3    0x55ef9b573452 postgres PostgresMain + 0x1413
4    0x55ef9b4d02b0 postgres <symbol not found> + 0x9b4d02b0
5    0x55ef9b4cf868 postgres <symbol not found> + 0x9b4cf868
6    0x55ef9b4cb0d6 postgres <symbol not found> + 0x9b4cb0d6
7    0x55ef9b4ca480 postgres PostmasterMain + 0x1405
8    0x55ef9b3b124e postgres <symbol not found> + 0x9b3b124e
9    0x7ffa03bb2083 libc.so.6 __libc_start_main + 0xf3
10   0x55ef9b012f9e postgres _start + 0x2e
"
2024-03-22 17:57:47.498681 +05,,,p85990,th46145024,,,,0,,,seg0,,,,,"LOG","00000","server process (PID 86688) was terminated by signal 6: Aborted","Failed process was running: select gid from pg_prepared_xacts where prepared < now() - interval'120 seconds'",,,,,,0,,"postmaster.c",4023,
```
Will approve after final CI run.

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1194248

**Review by InnerLife0 — APPROVED** [review]

**Comment by BenderArenadata** [comment]
Allure report https://allure.adsw.io/launch/67406

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1201709

**Comment by BenderArenadata** [comment]
Failed job Resource group isolation tests on ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1201710

**Pull request merged**
